create PROCEDURE [dbo].[Bills_Upsert] @BillID INT
	,@Bills [utt_Bills] readonly
	,@BillDetails [utt_BillDetails] readonly
	,@ItemSaleDetails [utt_ItemSaleDetails] readonly
	,@BillExpenses [utt_BillExpenses] readonly
AS
BEGIN

	IF OBJECT_ID('tempdb..#tmpItemSaleDetails') IS NOT NULL
			DROP TABLE #tmpItemSaleDetails;
	SELECT	 ItemSaleDetailID ,ItemSaleDetailNo ,ItemSaleCode ,ItemSaleCodeDetail ,fkAccountID
				,PhoneNo ,IsCompanyAccount ,fkBillDetailID ,Quantity ,Rate ,SaleTypeFixOrWeightBased
				,GrossWeight ,WeightDetails ,NetWeight ,CommissionPercent ,CommissionAmount ,TotalAmount
				,fkBranchID ,IsActive ,CreateBy ,CreateDate ,ModifyBy ,ModifyDate ,@BillID AS fkBillID
				,Remark ,Comment ,PaidAmount ,Discount ,RemainingAmount ,IsPanaPaid ,tempBillDetailID
		INTO #tmpItemSaleDetails
		FROM @ItemSaleDetails tmp;

	IF (isnull(@BillID, 0) = 0)
	BEGIN
		INSERT INTO [Bills] (
			[BillNo]
			,[BillCode]
			,[BillCodeDetail]
			,[fkAccountID]
			,[IsCompanyAccount]
			,[FirmPhoneNo]
			,[BillRsvrPersonName]
			,[BillRsvrPhoneNo]
			,[fkVillageID]
			,[VillageName]
			,[BillDate]
			,[BillPaidStatus]
			,[IsBillPrint]
			,[fkBillTypeID]
			,[BillType]
			,[fkGadiMasterID]
			,[TransPortName]
			,[GadiNo]
			,[IsBhadaPaid]
			,[GadiBhada]
			,[PreviousBalance]
			,[TotalSevaSulk]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalKhadiKarai]
			,[TotalInam]
			,[TotalStationary]
			,[TotalPostageCharge]
			,[TotalOtherCharges]
			,[TotalPurchaseCommissionCharge]
			,[TotalQuantity]
			,[TotalAmount]
			,[TotalDeduction]
			,[NetAmount]
			,[PaidAmount]
			,[BalanceAmount]
			,[Discount]
			,[SalesTax]
			,[VatTax]
			,[OtherTax]
			,[Comments]
			,[PaymentMode]
			,[BillingAddress]
			,[ShipingAddress]
			,[fkBranchID]
			,[IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[ModifyDate]
			,[SendBillToMandiOffice]
			,[GateParchiNo]
			,[AnubandNo]
			,[TolParchiNo]
			,[Other1]
			,[Other2]
			,[Other3]
			,[Other4]
			,[Other5]
			,[AnubandNoSN]
			,[TolParchiNoSN]
			,[BhugtanNo]
			,[BhugtanNoSN]
			,[BookNo]
			,[AawakDate]
			,[BiltiNo]
			,[AddressDetail]
			,[StateDetails]
			,[BillPrintType]
			)
		SELECT [BillNo]
			,[BillCode]
			,[BillCodeDetail]
			,[fkAccountID]
			,[IsCompanyAccount]
			,[FirmPhoneNo]
			,[BillRsvrPersonName]
			,[BillRsvrPhoneNo]
			,[fkVillageID]
			,[VillageName]
			,[BillDate]
			,[BillPaidStatus]
			,[IsBillPrint]
			,[fkBillTypeID]
			,[BillType]
			,[fkGadiMasterID]
			,[TransPortName]
			,[GadiNo]
			,[IsBhadaPaid]
			,[GadiBhada]
			,[PreviousBalance]
			,[TotalSevaSulk]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalKhadiKarai]
			,[TotalInam]
			,[TotalStationary]
			,[TotalPostageCharge]
			,[TotalOtherCharges]
			,[TotalPurchaseCommissionCharge]
			,[TotalQuantity]
			,[TotalAmount]
			,[TotalDeduction]
			,[NetAmount]
			,[PaidAmount]
			,[BalanceAmount]
			,[Discount]
			,[SalesTax]
			,[VatTax]
			,[OtherTax]
			,[Comments]
			,[PaymentMode]
			,[BillingAddress]
			,[ShipingAddress]
			,[fkBranchID]
			,[IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[ModifyDate]
			,[SendBillToMandiOffice]
			,[GateParchiNo]
			,[AnubandNo]
			,[TolParchiNo]
			,[Other1]
			,[Other2]
			,[Other3]
			,[Other4]
			,[Other5]
			,[AnubandNoSN]
			,[TolParchiNoSN]
			,[BhugtanNo]
			,[BhugtanNoSN]
			,[BookNo]
			,[AawakDate]
			,[BiltiNo]
			,[AddressDetail]
			,[StateDetails]
			,[BillPrintType]
		FROM @Bills

		SET @BillID = @@IDENTITY;

		INSERT INTO [BillExpenses] (
			[BillExpenseNo]
			,[BillExpenseCode]
			,[fkBillID]
			,[TotalGadiBhada]
			,[TotalAdvance]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalBarwai]
			,[TotalMaidanHammali]
			,[TotalPalaKarai]
			,[TotalThelaBhada]
			,[TotalBardan]
			,[TotalOthersExp]
			,[TotalCommissionExp]
			,[TotalMandiTax]
			,[TotalLabourCharge]
			,[TotalDhulaiCharge]
			,[OtherExpense1]
			,[OtherExpense2]
			,[OtherExpense3]
			,[OtherExpense4]
			,[OtherExpense5]
			,[Other1]
			,[Other2]
			,[Other3]
			,[Other4]
			,[Other5]
			,[IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[GatePassAmount]
			,[StoreBhadaAmount]
			,[DalaAmount]
			)
		SELECT [BillExpenseNo]
			,[BillExpenseCode]
			,@BillID
			,[TotalGadiBhada]
			,[TotalAdvance]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalBarwai]
			,[TotalMaidanHammali]
			,[TotalPalaKarai]
			,[TotalThelaBhada]
			,[TotalBardan]
			,[TotalOthersExp]
			,[TotalCommissionExp]
			,[TotalMandiTax]
			,[TotalLabourCharge]
			,[TotalDhulaiCharge]
			,[OtherExpense1]
			,[OtherExpense2]
			,[OtherExpense3]
			,[OtherExpense4]
			,[OtherExpense5]
			,[Other1]
			,[Other2]
			,[Other3]
			,[Other4]
			,[Other5]
			,[IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[GatePassAmount]
			,[StoreBhadaAmount]
			,[DalaAmount]
		FROM @BillExpenses
		
		INSERT INTO [BillDetails] (
			[BillDetailNo]
			,[BillDetailCode]
			,[fkBillID]
			,[SNo]
			,[fkItemTypeID]
			,[ItemName]
			,[fkItemUnitID]
			,[ItemUnit]
			,[ItemMarca]
			,[Quantity]
			,[ActualRate]
			,[BillRate]
			,[WeightDetails]
			,[BillWeightDetails]
			,[GrossWeight]
			,[BillGrossWeight]
			,[NetWeight]
			,[BillNetWeight]
			,[SaleTypeFixOrWeightBased]
			,[CommissionAmount]
			,[TotalWeightCutting]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalKhadiKari]
			,[ActualTotalAmount]
			,[BillTotalAmount]
			,[fkBranchID]
			,[IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[ModifyDate]
			,[CommissionPercent]
			,[AvgWeight]
			,[CommissionPercentS]
			,[CommissionAmountS]
			,[AvgRate]
			)
		SELECT [BillDetailNo]
			,[BillDetailCode]
			,@BillID
			,[SNo]
			,[fkItemTypeID]
			,[ItemName]
			,[fkItemUnitID]
			,[ItemUnit]
			,[ItemMarca]
			,[Quantity]
			,[ActualRate]
			,[BillRate]
			,[WeightDetails]
			,[BillWeightDetails]
			,[GrossWeight]
			,[BillGrossWeight]
			,[NetWeight]
			,[BillNetWeight]
			,[SaleTypeFixOrWeightBased]
			,[CommissionAmount]
			,[TotalWeightCutting]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalKhadiKari]
			,[ActualTotalAmount]
			,[BillTotalAmount]
			,[fkBranchID]
			,'1' [IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[ModifyDate]
			,[CommissionPercent]
			,[AvgWeight]
			,[CommissionPercentS]
			,[CommissionAmountS]
			,[AvgRate]
		FROM @BillDetails

		UPDATE #tmpItemSaleDetails
		SET fkBillID =@BillID 

		UPDATE TMP
		SET fkBillDetailID = BDS.BillDetailID
		FROM BillDetails bds
		INNER JOIN #tmpItemSaleDetails tmp on tmp.fkBillID = bds.fkBillID and tmp.tempBillDetailID = bds.SNo
		WHERE bds.fkBillID = @BillID;
		INSERT INTO [dbo].[ItemSaleDetails]
			([ItemSaleDetailNo] ,[ItemSaleCode] ,[ItemSaleCodeDetail] ,[fkAccountID] ,[PhoneNo] ,[IsCompanyAccount] 
			,[fkBillDetailID] ,[Quantity] ,[Rate] ,[SaleTypeFixOrWeightBased] ,[GrossWeight] ,[WeightDetails] ,[NetWeight] 
			,[CommissionPercent] ,[CommissionAmount] ,[TotalAmount] ,[fkBranchID] ,[IsActive] ,[CreateBy] ,[CreateDate] 
			,[ModifyBy] ,[ModifyDate] ,[fkBillID] ,[Remark] ,[Comment] )
			 SELECT ItemSaleDetailNo ,ItemSaleCode ,ItemSaleCodeDetail ,fkAccountID ,PhoneNo ,IsCompanyAccount
			,fkBillDetailID ,Quantity ,Rate ,SaleTypeFixOrWeightBased ,GrossWeight ,WeightDetails ,NetWeight ,CommissionPercent
			,CommissionAmount ,TotalAmount ,fkBranchID ,IsActive ,CreateBy ,CreateDate ,ModifyBy ,ModifyDate ,fkBillID
			,Remark ,Comment 
			FROM #tmpItemSaleDetails;
	END
	ELSE
	BEGIN
		
		UPDATE #tmpItemSaleDetails
		SET fkBillID =@BillID 
		
		UPDATE [dbo].[Bills]
		SET [BillNo] = utt.[BillNo]
			,[BillCode] = utt.[BillCode]
			,[BillCodeDetail] = utt.[BillCodeDetail]
			,[fkAccountID] = utt.[fkAccountID]
			,[IsCompanyAccount] = utt.[IsCompanyAccount]
			,[FirmPhoneNo] = utt.[FirmPhoneNo]
			,[BillRsvrPersonName] = utt.[BillRsvrPersonName]
			,[BillRsvrPhoneNo] = utt.[BillRsvrPhoneNo]
			,[fkVillageID] = utt.[fkVillageID]
			,[VillageName] = utt.[VillageName]
			,[BillDate] = utt.[BillDate]
			,[BillPaidStatus] = utt.[BillPaidStatus]
			,[IsBillPrint] = utt.[IsBillPrint]
			,[fkBillTypeID] = utt.[fkBillTypeID]
			,[BillType] = utt.[BillType]
			,[fkGadiMasterID] = utt.[fkGadiMasterID]
			,[TransPortName] = utt.[TransPortName]
			,[GadiNo] = utt.[GadiNo]
			,[IsBhadaPaid] = utt.[IsBhadaPaid]
			,[GadiBhada] = utt.[GadiBhada]
			,[PreviousBalance] = utt.[PreviousBalance]
			,[TotalSevaSulk] = utt.[TotalSevaSulk]
			,[TotalHammali] = utt.[TotalHammali]
			,[TotalTulai] = utt.[TotalTulai]
			,[TotalKhadiKarai] = utt.[TotalKhadiKarai]
			,[TotalInam] = utt.[TotalInam]
			,[TotalStationary] = utt.[TotalStationary]
			,[TotalPostageCharge] = utt.[TotalPostageCharge]
			,[TotalOtherCharges] = utt.[TotalOtherCharges]
			,[TotalPurchaseCommissionCharge] = utt.[TotalPurchaseCommissionCharge] 
			,[TotalQuantity] = utt.[TotalQuantity]
			,[TotalAmount] = utt.[TotalAmount]
			,[TotalDeduction] = utt.[TotalDeduction]
			,[NetAmount] = utt.[NetAmount]
			,[PaidAmount] = utt.[PaidAmount]
			,[BalanceAmount] = utt.[BalanceAmount]
			,[Discount] = utt.[Discount]
			,[SalesTax] = utt.[SalesTax]
			,[VatTax] = utt.[VatTax]
			,[OtherTax] = utt.[OtherTax]
			,[Comments] = utt.[Comments]
			,[PaymentMode] = utt.[PaymentMode]
			,[BillingAddress] = utt.[BillingAddress]
			,[ShipingAddress] = utt.[ShipingAddress]
			,[fkBranchID] = utt.[fkBranchID]
			,[IsActive] = utt.[IsActive]
			,[CreateBy] = utt.[CreateBy]
			,[CreateDate] = utt.[CreateDate]
			,[ModifyBy] = utt.[ModifyBy]
			,[ModifyDate] = utt.[ModifyDate]
			,[SendBillToMandiOffice] = utt.[SendBillToMandiOffice]
			,[GateParchiNo] = utt.[GateParchiNo]
			,[AnubandNo] = utt.[AnubandNo]
			,[TolParchiNo] = utt.[TolParchiNo]
			,[Other1] = utt.[Other1]
			,[Other2] = utt.[Other2]
			,[Other3] = utt.[Other3]
			,[Other4] = utt.[Other4]
			,[Other5] = utt.[Other5]
			,[AnubandNoSN] = utt.[AnubandNoSN]
			,[TolParchiNoSN] = utt.[TolParchiNoSN]
			,[BhugtanNo] = utt.[BhugtanNo]
			,[BhugtanNoSN] = utt.[BhugtanNoSN]
			,[BookNo] = utt.[BookNo]
			,[AawakDate] = utt.[AawakDate]
			,[BiltiNo] = utt.[BiltiNo]
			,[AddressDetail] = utt.[AddressDetail]
			,[StateDetails] = utt.[StateDetails]
			,[BillPrintType] = utt.[BillPrintType]
		FROM bills b
		INNER JOIN @Bills utt ON b.BillID = utt.BillID
		
		UPDATE [dbo].[BillExpenses]
		SET [BillExpenseNo] = utt.[BillExpenseNo]
			,[BillExpenseCode] = utt.[BillExpenseCode]
			,[fkBillID] = utt.[fkBillID]
			,[TotalGadiBhada] = utt.[TotalGadiBhada]
			,[TotalAdvance] = utt.[TotalAdvance]
			,[TotalHammali] = utt.[TotalHammali]
			,[TotalTulai] = utt.[TotalTulai]
			,[TotalBarwai] = utt.[TotalBarwai]
			,[TotalMaidanHammali] = utt.[TotalMaidanHammali]
			,[TotalPalaKarai] = utt.[TotalPalaKarai]
			,[TotalThelaBhada] = utt.[TotalThelaBhada]
			,[TotalBardan] = utt.[TotalBardan]
			,[TotalOthersExp] = utt.[TotalOthersExp]
			,[TotalCommissionExp] = utt.[TotalCommissionExp]
			,[TotalMandiTax] = utt.[TotalMandiTax]
			,[TotalLabourCharge] = utt.[TotalLabourCharge]
			,[TotalDhulaiCharge] = utt.[TotalDhulaiCharge]
			,[OtherExpense1] = utt.[OtherExpense1]
			,[OtherExpense2] = utt.[OtherExpense2]
			,[OtherExpense3] = utt.[OtherExpense3]
			,[OtherExpense4] = utt.[OtherExpense4]
			,[OtherExpense5] = utt.[OtherExpense5]
			,[Other1] = utt.[Other1]
			,[Other2] = utt.[Other2]
			,[Other3] = utt.[Other3]
			,[Other4] = utt.[Other4]
			,[Other5] = utt.[Other5]
			,[IsActive] = utt.[IsActive]
			,[CreateBy] = utt.[CreateBy]
			,[CreateDate] = utt.[CreateDate]
			,[ModifyBy] = utt.[ModifyBy]
			,[GatePassAmount] = utt.[GatePassAmount]
			,[StoreBhadaAmount] = utt.[StoreBhadaAmount]
			,[DalaAmount] = utt.[DalaAmount]
		FROM [BillExpenses] be
		INNER JOIN @BillExpenses utt ON be.BillExpenseID = utt.BillExpenseID
		and be.BillExpenseCode = utt.BillExpenseCode

		UPDATE [BillDetails]
		SET [BillDetailNo] = utt.[BillDetailNo]
			,[BillDetailCode] = utt.[BillDetailCode]
			,[fkBillID] = utt.[fkBillID]
			,[SNo] = utt.[SNo]
			,[fkItemTypeID] = utt.[fkItemTypeID]
			,[ItemName] = utt.[ItemName]
			,[fkItemUnitID] = utt.[fkItemUnitID]
			,[ItemUnit] = utt.[ItemUnit]
			,[ItemMarca] = utt.[ItemMarca]
			,[Quantity] = utt.[Quantity]
			,[ActualRate] = utt.[ActualRate]
			,[BillRate] = utt.[BillRate]
			,[WeightDetails] = utt.[WeightDetails]
			,[BillWeightDetails] = utt.[BillWeightDetails]
			,[GrossWeight] = utt.[GrossWeight]
			,[BillGrossWeight] = utt.[BillGrossWeight]
			,[NetWeight] = utt.[NetWeight]
			,[BillNetWeight] = utt.[BillNetWeight]
			,[SaleTypeFixOrWeightBased] = utt.[SaleTypeFixOrWeightBased]
			,[CommissionAmount] = utt.[CommissionAmount]
			,[TotalWeightCutting] = utt.[TotalWeightCutting]
			,[TotalHammali] = utt.[TotalHammali]
			,[TotalTulai] = utt.[TotalTulai]
			,[TotalKhadiKari] = utt.[TotalKhadiKari]
			,[ActualTotalAmount] = utt.[ActualTotalAmount]
			,[BillTotalAmount] = utt.[BillTotalAmount]
			,[fkBranchID] = utt.[fkBranchID]
			,[IsActive] = utt.[IsActive]
			,[CreateBy] = utt.[CreateBy]
			,[CreateDate] = utt.[CreateDate]
			,[ModifyBy] = utt.[ModifyBy]
			,[ModifyDate] = utt.[ModifyDate]
			,[CommissionPercent] = utt.[CommissionPercent]
			,[AvgWeight] = utt.[AvgWeight]
			,[CommissionPercentS] = utt.[CommissionPercentS]
			,[CommissionAmountS] = utt.[CommissionAmountS]
			,[AvgRate] = utt.[AvgRate]
		FROM BillDetails bd
		INNER JOIN @BillDetails utt ON bd.BillDetailID = utt.BillDetailID

		INSERT INTO [BillDetails] (
			[BillDetailNo]
			,[BillDetailCode]
			,[fkBillID]
			,[SNo]
			,[fkItemTypeID]
			,[ItemName]
			,[fkItemUnitID]
			,[ItemUnit]
			,[ItemMarca]
			,[Quantity]
			,[ActualRate]
			,[BillRate]
			,[WeightDetails]
			,[BillWeightDetails]
			,[GrossWeight]
			,[BillGrossWeight]
			,[NetWeight]
			,[BillNetWeight]
			,[SaleTypeFixOrWeightBased]
			,[CommissionAmount]
			,[TotalWeightCutting]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalKhadiKari]
			,[ActualTotalAmount]
			,[BillTotalAmount]
			,[fkBranchID]
			,[IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[ModifyDate]
			,[CommissionPercent]
			,[AvgWeight]
			,[CommissionPercentS]
			,[CommissionAmountS]
			,[AvgRate]
			)
		SELECT bdt.[BillDetailNo]
			,bdt.[BillDetailCode]
			,@BillID
			,bdt.[SNo]
			,bdt.[fkItemTypeID]
			,bdt.[ItemName]
			,bdt.[fkItemUnitID]
			,bdt.[ItemUnit]
			,bdt.[ItemMarca]
			,bdt.[Quantity]
			,bdt.[ActualRate]
			,bdt.[BillRate]
			,bdt.[WeightDetails]
			,bdt.[BillWeightDetails]
			,bdt.[GrossWeight]
			,bdt.[BillGrossWeight]
			,bdt.[NetWeight]
			,bdt.[BillNetWeight]
			,bdt.[SaleTypeFixOrWeightBased]
			,bdt.[CommissionAmount]
			,bdt.[TotalWeightCutting]
			,bdt.[TotalHammali]
			,bdt.[TotalTulai]
			,bdt.[TotalKhadiKari]
			,bdt.[ActualTotalAmount]
			,bdt.[BillTotalAmount]
			,bdt.[fkBranchID]
			,'1' [IsActive]
			,bdt.[CreateBy]
			,bdt.[CreateDate]
			,bdt.[ModifyBy]
			,bdt.[ModifyDate]
			,bdt.[CommissionPercent]
			,bdt.[AvgWeight]
			,bdt.[CommissionPercentS]
			,bdt.[CommissionAmountS]
			,bdt.[AvgRate]
		FROM @BillDetails bdt
		left join BillDetails bd on bdt.fkBillID = bd.fkBillID
			and bd.BillDetailID = bdt.BillDetailID 
			where bd.BillDetailID is null

		update bd set IsActive = '0'
		FROM BillDetails bd
		left join  @BillDetails bdt on bdt.fkBillID = bd.fkBillID
			and bd.BillDetailID = bdt.BillDetailID 
			where bdt.BillDetailID is null

		UPDATE TMP
		SET fkBillDetailID = BDS.BillDetailID
		FROM BillDetails bds
		INNER JOIN #tmpItemSaleDetails tmp on tmp.fkBillID = bds.fkBillID and tmp.tempBillDetailID = bds.SNo
		WHERE bds.fkBillID = @BillID;

		INSERT INTO [dbo].[ItemSaleDetails]
			([ItemSaleDetailNo] ,[ItemSaleCode] ,[ItemSaleCodeDetail] ,[fkAccountID] ,[PhoneNo] ,[IsCompanyAccount] 
			,[fkBillDetailID] ,[Quantity] ,[Rate] ,[SaleTypeFixOrWeightBased] ,[GrossWeight] ,[WeightDetails] ,[NetWeight] 
			,[CommissionPercent] ,[CommissionAmount] ,[TotalAmount] ,[fkBranchID] ,[IsActive] ,[CreateBy] ,[CreateDate] 
			,[ModifyBy] ,[ModifyDate] ,[fkBillID] ,[Remark] ,[Comment] )
		SELECT isdt.ItemSaleDetailNo ,isdt.ItemSaleCode ,isdt.ItemSaleCodeDetail ,isdt.fkAccountID ,isdt.PhoneNo ,isdt.IsCompanyAccount
			,isdt.fkBillDetailID ,isdt.Quantity ,isdt.Rate ,isdt.SaleTypeFixOrWeightBased ,isdt.GrossWeight ,isdt.WeightDetails ,isdt.NetWeight ,isdt.CommissionPercent
			,isdt.CommissionAmount ,isdt.TotalAmount ,isdt.fkBranchID ,isdt.IsActive ,isdt.CreateBy ,isdt.CreateDate ,isdt.ModifyBy ,isdt.ModifyDate ,isdt.fkBillID
			,isdt.Remark ,isdt.Comment 
			FROM #tmpItemSaleDetails isdt 
				left join [ItemSaleDetails] isd on
					isd.ItemSaleDetailID = isdt.ItemSaleDetailID 
			WHERE isd.ItemSaleDetailID is null
			;                                 
			
		update isd set IsActive = '0'
		FROM BillDetails bd
			inner join ItemSaleDetails isd on 
				bd.BillDetailID = isd.fkBillDetailID
				and bd.IsActive = '0'
			where bd.fkBillID = @BillID

	END

	Exec BillExpensesAT_Upsert @BillID, 'Purchase';

	SELECT @BillID BillID, BillNo, BillCode
	FROM @Bills;
END
