CREATE PROCEDURE [dbo].[ExportMasters_Upsert] (
	 @ExportMasterID INT
	,@ExportMasters utt_ExportMasters readonly
	,@ExportItemDetails utt_ExportItemDetails readonly
	,@ExportExpenses utt_ExportExpenses readonly
	)
AS
BEGIN
	IF (isnull(@ExportMasterID, 0) = 0)
	BEGIN
		-- Insert Case
		INSERT INTO [dbo].[ExportMasters] (
			[ExportMasterNo]
			,[ExportCode]
			,[ExportCodeDetail]
			,[fkAccountID]
			,[BiltiNo]
			,[IsExportBaki]
			,[IsExportBakiDetail]
			,[ExportMasterPaidStatus]
			,[BiltiDetail]
			,[BiltiDate]
			,[ClientName]
			,[fkVillageID]
			,[ClientCity]
			,[DriverName]
			,[DriverPhoneNo]
			,[DriverInam]
			,[GadiBhada]
			,[AdvanceBhada]
			,[RemainingBhada]
			,[ReachDate]
			,[TimeToReach]
			,[PerKattaBhada]
			,[PerCaratBhada]
			,[ParBoriBhada]
			,[FakeMandiAmount]
			,[FakeMandiPercent]
			,[FakeMandiNetAmount]
			,[TotalExportAmount]
			,[TotalBillExportAmount]
			,[TotalExpenses]
			,[BillTotalExpenses]
			,[NetExportAmount]
			,[BillNetExportAmount]
			,[GadiNo]
			,[TotalHammali]
			,[MandiSulk]
			,[fkBranchID]
			,[IsActive]
			,[InsertDate]
			,[ModifyDate]
			,[CreatedBy]
			,[ModifiedBy]
			,[Address]
			,[Transport]
			)
		SELECT [ExportMasterNo]
			,[ExportCode]
			,[ExportCodeDetail]
			,[fkAccountID]
			,[BiltiNo]
			,[IsExportBaki]
			,[IsExportBakiDetail]
			,[ExportMasterPaidStatus]
			,[BiltiDetail]
			,[BiltiDate]
			,[ClientName]
			,[fkVillageID]
			,[ClientCity]
			,[DriverName]
			,[DriverPhoneNo]
			,[DriverInam]
			,[GadiBhada]
			,[AdvanceBhada]
			,[RemainingBhada]
			,[ReachDate]
			,[TimeToReach]
			,[PerKattaBhada]
			,[PerCaratBhada]
			,[ParBoriBhada]
			,[FakeMandiAmount]
			,[FakeMandiPercent]
			,[FakeMandiNetAmount]
			,[TotalExportAmount]
			,[TotalBillExportAmount]
			,[TotalExpenses]
			,[BillTotalExpenses]
			,[NetExportAmount]
			,[BillNetExportAmount]
			,[GadiNo]
			,[TotalHammali]
			,[MandiSulk]
			,[fkBranchID]
			,[IsActive]
			,[InsertDate]
			,[ModifyDate]
			,[CreatedBy]
			,[ModifiedBy]
			,[Address]
			,[Transport]
		FROM @ExportMasters

		SET @ExportMasterID = Scope_identity()

		INSERT INTO [dbo].[ExportExpenses] (
			[ExportExpenseNo]
			,[ExportExpenseCode]
			,[fkExportID]
			,[TotalGadiBhada]
			,[TotalAdvance]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalBarwai]
			,[TotalMaidanHammali]
			,[TotalPalaKarai]
			,[TotalThelaBhada]
			,[TotalBardan]
			,[TotalOthersExp]
			,[TotalCommissionExp]
			,[TotalMandiTax]
			,[TotalLabourCharge]
			,[TotalDhulaiCharge]
			,[OtherExpense1]
			,[OtherExpense2]
			,[OtherExpense3]
			,[OtherExpense4]
			,[OtherExpense5]
			,[Other1]
			,[Other2]
			,[Other3]
			,[Other4]
			,[Other5]
			,[IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[GatePassAmount]
			,[StoreBhadaAmount]
			,[DalaAmount]
			)
		SELECT [ExportExpenseNo]
			,[ExportExpenseCode]
			,@ExportMasterID
			,[TotalGadiBhada]
			,[TotalAdvance]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalBarwai]
			,[TotalMaidanHammali]
			,[TotalPalaKarai]
			,[TotalThelaBhada]
			,[TotalBardan]
			,[TotalOthersExp]
			,[TotalCommissionExp]
			,[TotalMandiTax]
			,[TotalLabourCharge]
			,[TotalDhulaiCharge]
			,[OtherExpense1]
			,[OtherExpense2]
			,[OtherExpense3]
			,[OtherExpense4]
			,[OtherExpense5]
			,[Other1]
			,[Other2]
			,[Other3]
			,[Other4]
			,[Other5]
			,[IsActive]
			,[CreateBy]
			,[CreateDate]
			,[ModifyBy]
			,[GatePassAmount]
			,[StoreBhadaAmount]
			,[DalaAmount]
		FROM @ExportExpenses

		INSERT INTO [dbo].[ExportItemDetails] (
			[ExportItemDetailNo]
			,[ExportItemDetailCode]
			,[fkExportMasterID]
			,[fkItemSaleDetailID]
			,[ItemSaleDetails]
			,[IsCompanyAccount]
			,[fkAccountID]
			,[PartyName]
			,[PartyShortName]
			,[fkItemTypeID]
			,[ItemName]
			,[fkItemUnitID]
			,[UnitName]
			,[Marca]
			,[TotalQuantity]
			,[AcutualQuantity]
			,[BillQuantity]
			,[ActualRate]
			,[BillRate]
			,[GrossWeight]
			,[BillGrossWeight]
			,[NetWeight]
			,[BillNetWeight]
			,[TotalAmount]
			,[BillTotalAmount]
			,[CommissionPercent]
			,[CommissionPercent2]
			,[BillCommissionPercent]
			,[CommissionAmount]
			,[BillCommissionAmount]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalKhadiKari]
			,[NetAmount]
			,[BillNetAmount]
			,[TotalWeightCutting]
			,[lotDetail]
			,[TotalCarat]
			,[TotalCatte]
			,[TotalBhada]
			,[fkBranchID]
			,[IsActive]
			,[InsertDate]
			,[ModifyDate]
			,[CreatedBy]
			,[ModifiedBy]
			)
		SELECT [ExportItemDetailNo]
			,[ExportItemDetailCode]
			,@ExportMasterID
			,[fkItemSaleDetailID]
			,[ItemSaleDetails]
			,[IsCompanyAccount]
			,[fkAccountID]
			,[PartyName]
			,[PartyShortName]
			,[fkItemTypeID]
			,[ItemName]
			,[fkItemUnitID]
			,[UnitName]
			,[Marca]
			,[TotalQuantity]
			,[AcutualQuantity]
			,[BillQuantity]
			,[ActualRate]
			,[BillRate]
			,[GrossWeight]
			,[BillGrossWeight]
			,[NetWeight]
			,[BillNetWeight]
			,[TotalAmount]
			,[BillTotalAmount]
			,[CommissionPercent]
			,[CommissionPercent2]
			,[BillCommissionPercent]
			,[CommissionAmount]
			,[BillCommissionAmount]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalKhadiKari]
			,[NetAmount]
			,[BillNetAmount]
			,[TotalWeightCutting]
			,[lotDetail]
			,[TotalCarat]
			,[TotalCatte]
			,[TotalBhada]
			,[fkBranchID]
			,[IsActive]
			,[InsertDate]
			,[ModifyDate]
			,[CreatedBy]
			,[ModifiedBy]
		FROM @ExportItemDetails
	END
	ELSE
	BEGIN
		-- update Case
		UPDATE em
		SET [ExportMasterNo] = utt.[ExportMasterNo]
			,[ExportCode] = utt.[ExportCode]
			,[ExportCodeDetail] = utt.[ExportCodeDetail]
			,[fkAccountID] = utt.[fkAccountID]
			,[BiltiNo] = utt.[BiltiNo]
			,[IsExportBaki] = utt.[IsExportBaki]
			,[IsExportBakiDetail] = utt.[IsExportBakiDetail]
			,[ExportMasterPaidStatus] = utt.[ExportMasterPaidStatus]
			,[BiltiDetail] = utt.[BiltiDetail]
			,[BiltiDate] = utt.[BiltiDate]
			,[ClientName] = utt.[ClientName]
			,[fkVillageID] = utt.[fkVillageID]
			,[ClientCity] = utt.[ClientCity]
			,[DriverName] = utt.[DriverName]
			,[DriverPhoneNo] = utt.[DriverPhoneNo]
			,[DriverInam] = utt.[DriverInam]
			,[GadiBhada] = utt.[GadiBhada]
			,[AdvanceBhada] = utt.[AdvanceBhada]
			,[RemainingBhada] = utt.[RemainingBhada]
			,[ReachDate] = utt.[ReachDate]
			,[TimeToReach] = utt.[TimeToReach]
			,[PerKattaBhada] = utt.[PerKattaBhada]
			,[PerCaratBhada] = utt.[PerCaratBhada]
			,[ParBoriBhada] = utt.[ParBoriBhada]
			,[FakeMandiAmount] = utt.[FakeMandiAmount]
			,[FakeMandiPercent] = utt.[FakeMandiPercent]
			,[FakeMandiNetAmount] = utt.[FakeMandiNetAmount]
			,[TotalExportAmount] = utt.[TotalExportAmount]
			,[TotalBillExportAmount] = utt.[TotalBillExportAmount]
			,[TotalExpenses] = utt.[TotalExpenses]
			,[BillTotalExpenses] = utt.[BillTotalExpenses]
			,[NetExportAmount] = utt.[NetExportAmount]
			,[BillNetExportAmount] = utt.[BillNetExportAmount]
			,[GadiNo] = utt.[GadiNo]
			,[TotalHammali] = utt.[TotalHammali]
			,[MandiSulk] = utt.[MandiSulk]
			,[fkBranchID] = utt.[fkBranchID]
			,[IsActive] = utt.[IsActive]
			,[InsertDate] = utt.[InsertDate]
			,[ModifyDate] = utt.[ModifyDate]
			,[CreatedBy] = utt.[CreatedBy]
			,[ModifiedBy] = utt.[ModifiedBy]
			,[Address] = utt.[Address]
			,[Transport] = utt.[Transport]
		FROM [dbo].[ExportMasters] em
		INNER JOIN @ExportMasters utt ON utt.[ExportMasterID] = em.[ExportMasterID]

		UPDATE ee
		SET [ExportExpenseNo] = utt.[ExportExpenseNo]
			,[ExportExpenseCode] = utt.[ExportExpenseCode]
			,[fkExportID] = utt.[fkExportID]
			,[TotalGadiBhada] = utt.[TotalGadiBhada]
			,[TotalAdvance] = utt.[TotalAdvance]
			,[TotalHammali] = utt.[TotalHammali]
			,[TotalTulai] = utt.[TotalTulai]
			,[TotalBarwai] = utt.[TotalBarwai]
			,[TotalMaidanHammali] = utt.[TotalMaidanHammali]
			,[TotalPalaKarai] = utt.[TotalPalaKarai]
			,[TotalThelaBhada] = utt.[TotalThelaBhada]
			,[TotalBardan] = utt.[TotalBardan]
			,[TotalOthersExp] = utt.[TotalOthersExp]
			,[TotalCommissionExp] = utt.[TotalCommissionExp]
			,[TotalMandiTax] = utt.[TotalMandiTax]
			,[TotalLabourCharge] = utt.[TotalLabourCharge]
			,[TotalDhulaiCharge] = utt.[TotalDhulaiCharge]
			,[OtherExpense1] = utt.[OtherExpense1]
			,[OtherExpense2] = utt.[OtherExpense2]
			,[OtherExpense3] = utt.[OtherExpense3]
			,[OtherExpense4] = utt.[OtherExpense4]
			,[OtherExpense5] = utt.[OtherExpense5]
			,[Other1] = utt.[Other1]
			,[Other2] = utt.[Other2]
			,[Other3] = utt.[Other3]
			,[Other4] = utt.[Other4]
			,[Other5] = utt.[Other5]
			,[IsActive] = utt.[IsActive]
			,[CreateBy] = utt.[CreateBy]
			,[CreateDate] = utt.[CreateDate]
			,[ModifyBy] = utt.[ModifyBy]
			,[GatePassAmount] = utt.[GatePassAmount]
			,[StoreBhadaAmount] = utt.[StoreBhadaAmount]
			,[DalaAmount] = utt.[DalaAmount]
		FROM [ExportExpenses] ee
		INNER JOIN @ExportExpenses utt ON utt.[fkExportID] = ee.[fkExportID]

		UPDATE ed
		SET  [ExportItemDetailNo] = utt.[ExportItemDetailNo]--[ExportItemDetailID] = utt.[ExportItemDetailID],
			,[ExportItemDetailCode] = utt.[ExportItemDetailCode]
			,[fkExportMasterID] = utt.[fkExportMasterID]
			,[fkItemSaleDetailID] = utt.[fkItemSaleDetailID]
			,[ItemSaleDetails] = utt.[ItemSaleDetails]
			,[IsCompanyAccount] = utt.[IsCompanyAccount]
			,[fkAccountID] = utt.[fkAccountID]
			,[PartyName] = utt.[PartyName]
			,[PartyShortName] = utt.[PartyShortName]
			,[fkItemTypeID] = utt.[fkItemTypeID]
			,[ItemName] = utt.[ItemName]
			,[fkItemUnitID] = utt.[fkItemUnitID]
			,[UnitName] = utt.[UnitName]
			,[Marca] = utt.[Marca]
			,[TotalQuantity] = utt.[TotalQuantity]
			,[AcutualQuantity] = utt.[AcutualQuantity]
			,[BillQuantity] = utt.[BillQuantity]
			,[ActualRate] = utt.[ActualRate]
			,[BillRate] = utt.[BillRate]
			,[GrossWeight] = utt.[GrossWeight]
			,[BillGrossWeight] = utt.[BillGrossWeight]
			,[NetWeight] = utt.[NetWeight]
			,[BillNetWeight] = utt.[BillNetWeight]
			,[TotalAmount] = utt.[TotalAmount]
			,[BillTotalAmount] = utt.[BillTotalAmount]
			,[CommissionPercent] = utt.[CommissionPercent]
			,[CommissionPercent2] = utt.[CommissionPercent2]
			,[BillCommissionPercent] = utt.[BillCommissionPercent]
			,[CommissionAmount] = utt.[CommissionAmount]
			,[BillCommissionAmount] = utt.[BillCommissionAmount]
			,[TotalHammali] = utt.[TotalHammali]
			,[TotalTulai] = utt.[TotalTulai]
			,[TotalKhadiKari] = utt.[TotalKhadiKari]
			,[NetAmount] = utt.[NetAmount]
			,[BillNetAmount] = utt.[BillNetAmount]
			,[TotalWeightCutting] = utt.[TotalWeightCutting]
			,[lotDetail] = utt.[lotDetail]
			,[TotalCarat] = utt.[TotalCarat]
			,[TotalCatte] = utt.[TotalCatte]
			,[TotalBhada] = utt.[TotalBhada]
			,[fkBranchID] = utt.[fkBranchID]
			,[IsActive] = utt.[IsActive]
			,[InsertDate] = utt.[InsertDate]
			,[ModifyDate] = utt.[ModifyDate]
			,[CreatedBy] = utt.[CreatedBy]
			,[ModifiedBy] = utt.[ModifiedBy]
		FROM [dbo].[ExportItemDetails] ed
		INNER JOIN @ExportItemDetails utt ON ed.[fkItemSaleDetailID] = utt.[fkItemSaleDetailID]
			AND ed.[fkExportMasterID] = ed.[fkExportMasterID]

		INSERT INTO [dbo].[ExportItemDetails] (
			[ExportItemDetailNo]
			,[ExportItemDetailCode]
			,[fkExportMasterID]
			,[fkItemSaleDetailID]
			,[ItemSaleDetails]
			,[IsCompanyAccount]
			,[fkAccountID]
			,[PartyName]
			,[PartyShortName]
			,[fkItemTypeID]
			,[ItemName]
			,[fkItemUnitID]
			,[UnitName]
			,[Marca]
			,[TotalQuantity]
			,[AcutualQuantity]
			,[BillQuantity]
			,[ActualRate]
			,[BillRate]
			,[GrossWeight]
			,[BillGrossWeight]
			,[NetWeight]
			,[BillNetWeight]
			,[TotalAmount]
			,[BillTotalAmount]
			,[CommissionPercent]
			,[CommissionPercent2]
			,[BillCommissionPercent]
			,[CommissionAmount]
			,[BillCommissionAmount]
			,[TotalHammali]
			,[TotalTulai]
			,[TotalKhadiKari]
			,[NetAmount]
			,[BillNetAmount]
			,[TotalWeightCutting]
			,[lotDetail]
			,[TotalCarat]
			,[TotalCatte]
			,[TotalBhada]
			,[fkBranchID]
			,[IsActive]
			,[InsertDate]
			,[ModifyDate]
			,[CreatedBy]
			,[ModifiedBy]
			)
		SELECT edt.[ExportItemDetailNo]
			,edt.[ExportItemDetailCode]
			,@ExportMasterID
			,edt.[fkItemSaleDetailID]
			,edt.[ItemSaleDetails]
			,edt.[IsCompanyAccount]
			,edt.[fkAccountID]
			,edt.[PartyName]
			,edt.[PartyShortName]
			,edt.[fkItemTypeID]
			,edt.[ItemName]
			,edt.[fkItemUnitID]
			,edt.[UnitName]
			,edt.[Marca]
			,edt.[TotalQuantity]
			,edt.[AcutualQuantity]
			,edt.[BillQuantity]
			,edt.[ActualRate]
			,edt.[BillRate]
			,edt.[GrossWeight]
			,edt.[BillGrossWeight]
			,edt.[NetWeight]
			,edt.[BillNetWeight]
			,edt.[TotalAmount]
			,edt.[BillTotalAmount]
			,edt.[CommissionPercent]
			,edt.[CommissionPercent2]
			,edt.[BillCommissionPercent]
			,edt.[CommissionAmount]
			,edt.[BillCommissionAmount]
			,edt.[TotalHammali]
			,edt.[TotalTulai]
			,edt.[TotalKhadiKari]
			,edt.[NetAmount]
			,edt.[BillNetAmount]
			,edt.[TotalWeightCutting]
			,edt.[lotDetail]
			,edt.[TotalCarat]
			,edt.[TotalCatte]
			,edt.[TotalBhada]
			,edt.[fkBranchID]
			,edt.[IsActive]
			,edt.[InsertDate]
			,edt.[ModifyDate]
			,edt.[CreatedBy]
			,edt.[ModifiedBy]
		FROM @ExportItemDetails edt
		LEFT JOIN [ExportItemDetails] ed ON ed.[fkExportMasterID] = edt.[fkExportMasterID]
			AND ed.[fkItemSaleDetailID] = edt.[fkItemSaleDetailID]
		WHERE ed.[fkItemSaleDetailID] IS NULL

		DELETE
		FROM [ExportItemDetails]
		WHERE ExportItemDetailID = (
				SELECT ed.ExportItemDetailID
				FROM [ExportItemDetails] ed
				LEFT JOIN @ExportItemDetails edt ON ed.[fkExportMasterID] = edt.[fkExportMasterID]
					AND ed.[fkItemSaleDetailID] = edt.[fkItemSaleDetailID]
				WHERE edt.[fkItemSaleDetailID] IS NULL
					AND ed.fkExportMasterID = @ExportMasterID
				)
	END
Exec ExportExpensesAT_Upsert @ExportMasterID, 'Export';
END