CREATE TYPE [dbo].[utt_ExportItemDetails] AS TABLE (
	[ExportItemDetailID] [int] NOT NULL,
	[ExportItemDetailNo] [int] NULL,
	[ExportItemDetailCode] [varchar](100) NULL,
	[fkExportMasterID] [int] NULL,
	[fkItemSaleDetailID] [int] NULL,
	[ItemSaleDetails] [varchar](100) NULL,
	[IsCompanyAccount] [varchar](50) NULL,
	[fkAccountID] [bigint] NULL,
	[PartyName] [varchar](250) NULL,
	[PartyShortName] [varchar](250) NULL,
	[fkItemTypeID] [int] NOT NULL,
	[ItemName] [nvarchar](500) NULL,
	[fkItemUnitID] [int] NOT NULL,
	[UnitName] [nvarchar](500) NULL,
	[Marca] [nvarchar](250) NULL,
	[TotalQuantity] [bigint] NULL,
	[AcutualQuantity] [bigint] NULL,
	[BillQuantity] [bigint] NULL,
	[ActualRate] [decimal](18, 2) NULL,
	[BillRate] [decimal](18, 2) NULL,
	[GrossWeight] [decimal](18, 2) NULL,
	[BillGrossWeight] [decimal](18, 2) NULL,
	[NetWeight] [decimal](18, 2) NULL,
	[BillNetWeight] [decimal](18, 2) NULL,
	[TotalAmount] [decimal](18, 2) NULL,
	[BillTotalAmount] [decimal](18, 2) NULL,
	[CommissionPercent] [decimal](18, 2) NULL,
	[CommissionPercent2] [decimal](18, 2) NULL,
	[BillCommissionPercent] [decimal](18, 2) NULL,
	[CommissionAmount] [decimal](18, 2) NULL,
	[BillCommissionAmount] [decimal](18, 2) NULL,
	[TotalHammali] [decimal](10, 2) NULL,
	[TotalTulai] [decimal](10, 2) NULL,
	[TotalKhadiKari] [decimal](10, 2) NULL,
	[NetAmount] [decimal](18, 2) NULL,
	[BillNetAmount] [decimal](18, 2) NULL,
	[TotalWeightCutting] [decimal](10, 2) NULL,
	[lotDetail] [nvarchar](250) NULL,
	[TotalCarat] [int] NULL,
	[TotalCatte] [int] NULL,
	[TotalBhada] [int] NULL,
	[fkBranchID] [int] NULL,
	[IsActive] [varchar](20) NULL,
	[InsertDate] [datetime] NULL,
	[ModifyDate] [datetime] NULL,
	[CreatedBy] [int] NULL,
	[ModifiedBy] [int] NULL
)