CREATE Type [dbo].[utt_ExportMasters] AS TABLE (
	[ExportMasterID] [int]  NOT NULL,
	[ExportMasterNo] [int] NULL,
	[ExportCode] [varchar](100) NULL,
	[ExportCodeDetail] [varchar](100) NULL,
	[fkAccountID] [bigint] NULL,
	[BiltiNo] [int] NULL,
	[IsExportBaki] [varchar](50) NULL,
	[IsExportBakiDetail] [varchar](250) NULL,
	[ExportMasterPaidStatus] [varchar](50) NULL,
	[BiltiDetail] [varchar](100) NULL,
	[BiltiDate] [datetime] NULL,
	[ClientName] [nvarchar](500) NULL,
	[fkVillageID] [bigint] NULL,
	[ClientCity] [nvarchar](500) NULL,
	[DriverName] [nvarchar](500) NULL,
	[DriverPhoneNo] [nvarchar](500) NULL,
	[DriverInam] [nvarchar](250) NULL,
	[GadiBhada] [decimal](18, 2) NULL,
	[AdvanceBhada] [decimal](18, 2) NULL,
	[RemainingBhada] [decimal](18, 2) NULL,
	[ReachDate] [datetime] NULL,
	[TimeToReach] [nvarchar](250) NULL,
	[PerKattaBhada] [decimal](18, 2) NULL,
	[PerCaratBhada] [decimal](18, 2) NULL,
	[ParBoriBhada] [decimal](18, 2) NULL,
	[FakeMandiAmount] [decimal](18, 2) NULL,
	[FakeMandiPercent] [decimal](18, 2) NULL,
	[FakeMandiNetAmount] [decimal](18, 2) NULL,
	[TotalExportAmount] [decimal](18, 2) NULL,
	[TotalBillExportAmount] [decimal](18, 2) NULL,
	[TotalExpenses] [decimal](18, 2) NULL,
	[BillTotalExpenses] [decimal](18, 2) NULL,
	[NetExportAmount] [decimal](18, 2) NULL,
	[BillNetExportAmount] [decimal](18, 2) NULL,
	[GadiNo] [varchar](50) NULL,
	[TotalHammali] [decimal](18, 2) NULL,
	[MandiSulk] [decimal](18, 2) NULL,
	[fkBranchID] [int] NULL,
	[IsActive] [varchar](20) NULL,
	[InsertDate] [datetime] NULL,
	[ModifyDate] [datetime] NULL,
	[CreatedBy] [int] NULL,
	[ModifiedBy] [int] NULL,
	[Address] [varchar](1000) NULL,
	[Transport] [varchar](500) NULL
)