CREATE TYPE [dbo].[utt_BillExpenses] AS TABLE
(
	[BillExpenseID]      BIGINT          NOT NULL,
    [BillExpenseNo]      BIGINT          NOT NULL,
    [BillExpenseCode]    VARCHAR (100)   NULL,
    [fkBillID]           INT             NULL,
    [TotalGadiBhada]     DECIMAL (10, 2) NULL,
    [TotalAdvance]       DECIMAL (10, 2) NULL,
    [TotalHammali]       DECIMAL (10, 2) NULL,
    [TotalTulai]         DECIMAL (10, 2) NULL,
    [TotalBarwai]        DECIMAL (10, 2) NULL,
    [TotalMaidanHammali] DECIMAL (10, 2) NULL,
    [TotalPalaKarai]     DECIMAL (10, 2) NULL,
    [TotalThelaBhada]    DECIMAL (10, 2) NULL,
    [TotalBardan]        DECIMAL (10, 2) NULL,
    [TotalOthersExp]     DECIMAL (10, 2) NULL,
    [TotalCommissionExp] DECIMAL (10, 2) NULL,
    [TotalMandiTax]      DECIMAL (10, 2) NULL,
    [TotalLabourCharge]  DECIMAL (10, 2) NULL,
    [TotalDhulaiCharge]  DECIMAL (10, 2) NULL,
    [OtherExpense1]      DECIMAL (10, 2) NULL,
    [OtherExpense2]      DECIMAL (10, 2) NULL,
    [OtherExpense3]      DECIMAL (10, 2) NULL,
    [OtherExpense4]      DECIMAL (10, 2) NULL,
    [OtherExpense5]      DECIMAL (10, 2) NULL,
    [Other1]             VARCHAR (250)   NULL,
    [Other2]             VARCHAR (250)   NULL,
    [Other3]             VARCHAR (250)   NULL,
    [Other4]             VARCHAR (250)   NULL,
    [Other5]             VARCHAR (250)   NULL,
    [IsActive]           VARCHAR (20)    NULL,
    [CreateBy]           INT             NULL,
    [CreateDate]         DATETIME        NULL,
    [ModifyBy]           INT             NULL,
    [GatePassAmount]     DECIMAL (10, 2) NULL,
    [StoreBhadaAmount]   DECIMAL (10, 2) NULL,
    [DalaAmount]         DECIMAL (10, 2) NULL
)


