CREATE TYPE [dbo].[utt_BillDetails] AS TABLE
(
	 [BillDetailID]             BIGINT         NOT NULL,
    [BillDetailNo]             BIGINT          NULL,
    [BillDetailCode]           VARCHAR (100)   NULL,
    [fkBillID]                 BIGINT          NULL,
    [SNo]                      INT             NULL,
    [fkItemTypeID]             INT             NOT NULL,
    [ItemName]                 NVARCHAR (500)  NULL,
    [fkItemUnitID]             INT             NOT NULL,
    [ItemUnit]                 NVARCHAR (500)  NULL,
    [ItemMarca]                NVARCHAR (50)   NULL,
    [Quantity]                 DECIMAL (10)    NULL,
    [ActualRate]               DECIMAL (18, 2) NULL,
    [BillRate]                 DECIMAL (18, 2) NULL,
    [WeightDetails]            VARCHAR (4000)  NULL,
    [BillWeightDetails]        VARCHAR (4000)  NULL,
    [GrossWeight]              DECIMAL (18, 2) NULL,
    [BillGrossWeight]          DECIMAL (18, 2) NULL,
    [NetWeight]                DECIMAL (18, 2) NULL,
    [BillNetWeight]            DECIMAL (18, 2) NULL,
    [SaleTypeFixOrWeightBased] NVARCHAR (50)   NULL,
    [CommissionAmount]         DECIMAL (18, 2) NULL,
    [TotalWeightCutting]       DECIMAL (10, 2) NULL,
    [TotalHammali]             DECIMAL (10, 2) NULL,
    [TotalTulai]               DECIMAL (10, 2) NULL,
    [TotalKhadiKari]           DECIMAL (10, 2) NULL,
    [ActualTotalAmount]        DECIMAL (18, 2) NULL,
    [BillTotalAmount]          DECIMAL (18, 2) NULL,
    [fkBranchID]               INT             NULL,
    [IsActive]                 VARCHAR (20)    NULL,
    [CreateBy]                 INT             NULL,
    [CreateDate]               DATETIME        NULL,
    [ModifyBy]                 INT             NULL,
    [ModifyDate]               DATETIME        NULL,
    [CommissionPercent]        DECIMAL (10, 2) NULL,
    [AvgWeight]                DECIMAL (10, 2) NULL,
    [CommissionPercentS] DECIMAL(10, 2) NULL, 
    [CommissionAmountS]         DECIMAL (18, 2) NULL,
    [AvgRate] DECIMAL(10, 2) NULL
)

