CREATE TYPE [dbo].[utt_ItemSaleDetails] AS TABLE
(
	[ItemSaleDetailID] [bigint] NOT NULL,
	[ItemSaleDetailNo] [bigint] NULL,
	[ItemSaleCode] [varchar](100) NULL,
	[ItemSaleCodeDetail] [varchar](100) NULL,
	[fkAccountID] [bigint] NULL,
	[PhoneNo] [varchar](50) NULL,
	[IsCompanyAccount] [varchar](50) NULL,
	[fkBillDetailID] [bigint] NOT NULL,
	[Quantity] [decimal](10, 0) NULL,
	[Rate] [decimal](18, 2) NULL,
	[SaleTypeFixOrWeightBased] [nvarchar](50) NULL,
	[GrossWeight] [decimal](18, 2) NULL,
	[WeightDetails] [varchar](4000) NULL,
	[NetWeight] [decimal](18, 2) NULL,
	[CommissionPercent] [decimal](18, 2) NULL,
	[CommissionAmount] [decimal](18, 2) NULL,
	[TotalAmount] [decimal](18, 2) NULL,
	[fkBranchID] [int] NULL,
	[IsActive] [varchar](20) NULL,
	[CreateBy] [int] NULL,
	[CreateDate] [datetime] NULL,
	[ModifyBy] [int] NULL,
	[ModifyDate] [datetime] NULL,
	[fkBillID] [bigint] NULL,
	[Remark] [varchar](max) NULL,
	[Comment] [varchar](max) NULL,
	[PaidAmount] [decimal](10, 2) NULL,
	[Discount] [decimal](10, 2) NULL,
	[RemainingAmount] [decimal](10, 2) NULL,
	[IsPanaPaid] [bit] NULL,
	[tempBillDetailID] [bigint] NULL
	)