CREATE  TYPE [dbo].[utt_ExportExpenses] AS TABLE (
	[ExportExpenseID] [bigint]  NOT NULL,
	[ExportExpenseNo] [bigint] NOT NULL,
	[ExportExpenseCode] [varchar](100) NULL,
	[fkExportID] [int] NULL,
	[TotalGadiBhada] [decimal](10, 2) NULL,
	[TotalAdvance] [decimal](10, 2) NULL,
	[TotalHammali] [decimal](10, 2) NULL,
	[TotalTulai] [decimal](10, 2) NULL,
	[TotalBarwai] [decimal](10, 2) NULL,
	[TotalMaidanHammali] [decimal](10, 2) NULL,
	[TotalPalaKarai] [decimal](10, 2) NULL,
	[TotalThelaBhada] [decimal](10, 2) NULL,
	[TotalBardan] [decimal](10, 2) NULL,
	[TotalOthersExp] [decimal](10, 2) NULL,
	[TotalCommissionExp] [decimal](10, 2) NULL,
	[TotalMandiTax] [decimal](10, 2) NULL,
	[TotalLabourCharge] [decimal](10, 2) NULL,
	[TotalDhulaiCharge] [decimal](10, 2) NULL,
	[OtherExpense1] [decimal](10, 2) NULL,
	[OtherExpense2] [decimal](10, 2) NULL,
	[OtherExpense3] [decimal](10, 2) NULL,
	[OtherExpense4] [decimal](10, 2) NULL,
	[OtherExpense5] [decimal](10, 2) NULL,
	[Other1] [varchar](250) NULL,
	[Other2] [varchar](250) NULL,
	[Other3] [varchar](250) NULL,
	[Other4] [varchar](250) NULL,
	[Other5] [varchar](250) NULL,
	[IsActive] [varchar](20) NULL,
	[CreateBy] [int] NULL,
	[CreateDate] [datetime] NULL,
	[ModifyBy] [int] NULL,
	[GatePassAmount] [decimal](10, 2) NULL,
	[StoreBhadaAmount] [decimal](10, 2) NULL,
	[DalaAmount] [decimal](10, 2) NULL
)

