
CREATE PROCEDURE [dbo].[BillDetails_UpdateByID] 
	(
@BillDetailID bigint,
@BillDetailNo bigint=null,
@BillDetailCode varchar(100)=null,
@fkBillID bigint=null,
@SNo int=null,
@fkItemTypeID int,
@ItemName nvarchar(500)=null,
@fkItemUnitID int,
@ItemUnit nvarchar(500)=null,
@ItemMarca nvarchar(50)=null,
@Quantity decimal=null,
@ActualRate decimal=null,
@BillRate decimal=null,
@WeightDetails varchar(4000)=null,
@BillWeightDetails varchar(4000)=null,
@GrossWeight decimal=null,
@BillGrossWeight decimal=null,
@NetWeight decimal=null,
@BillNetWeight decimal=null,
@SaleTypeFixOrWeightBased nvarchar(50)=null,
@CommissionAmount decimal=null,
@TotalWeightCutting decimal=null,
@TotalHammali decimal=null,
@TotalTulai decimal=null,
@TotalKhadiKari decimal=null,
@ActualTotalAmount decimal=null,
@BillTotalAmount decimal=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@CreateBy int=null,
@CreateDate datetime=null,
@ModifyBy int=null,
@ModifyDate datetime=null,
@CommissionPercent decimal=null,
@Sysdate datetime=null,
@AvgWeight decimal=null,
@CommissionPercentS decimal=null,
@CommissionAmountS decimal=null,
@AvgRate decimal=null
)
AS
Update  BillDetails Set 
[BillDetailNo]=@BillDetailNo,
[BillDetailCode]=@BillDetailCode,
[fkBillID]=@fkBillID,
[SNo]=@SNo,
[fkItemTypeID]=@fkItemTypeID,
[ItemName]=@ItemName,
[fkItemUnitID]=@fkItemUnitID,
[ItemUnit]=@ItemUnit,
[ItemMarca]=@ItemMarca,
[Quantity]=@Quantity,
[ActualRate]=@ActualRate,
[BillRate]=@BillRate,
[WeightDetails]=@WeightDetails,
[BillWeightDetails]=@BillWeightDetails,
[GrossWeight]=@GrossWeight,
[BillGrossWeight]=@BillGrossWeight,
[NetWeight]=@NetWeight,
[BillNetWeight]=@BillNetWeight,
[SaleTypeFixOrWeightBased]=@SaleTypeFixOrWeightBased,
[CommissionAmount]=@CommissionAmount,
[TotalWeightCutting]=@TotalWeightCutting,
[TotalHammali]=@TotalHammali,
[TotalTulai]=@TotalTulai,
[TotalKhadiKari]=@TotalKhadiKari,
[ActualTotalAmount]=@ActualTotalAmount,
[BillTotalAmount]=@BillTotalAmount,
[fkBranchID]=@fkBranchID,
[IsActive]=@IsActive,
[CreateBy]=@CreateBy,
[CreateDate]=@CreateDate,
[ModifyBy]=@ModifyBy,
[ModifyDate]=@ModifyDate,
[CommissionPercent]=@CommissionPercent,
[Sysdate]=@Sysdate,
[AvgWeight]=@AvgWeight,
[CommissionPercentS]=@CommissionPercentS,
[CommissionAmountS]=@CommissionAmountS,
[AvgRate]=@AvgRate
 
where 
[BillDetailID]=@BillDetailID


Return
