Create PROCEDURE [dbo].[BillPaymentDetails_Get] 
AS
Select 
[BillPaymentDeatilID],
[fkBillID],
[CompanyBankAccountID],
[PaymentMode],
[CashAmount],
[fkAccountBankDetailID],
[ChequeDate],
[ChequeNo],
[ChequeAmount],
[BankAccountNo],
[BranchNo],
[BranchName],
[IfscCode],
[PanNo],
[AccountHolderName],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[TransactionNo],
[Remark],
[Sysdate]

from 
BillPaymentDetails
Return
