
CREATE PROCEDURE [dbo].[BillMasters_Insert] 
	(
@fkBillID bigint,
@fkAccountID bigint,
@IsCompanyAccount varchar(50)=null,
@BillPaidStatus varchar(50)=null,
@IsCapital varchar(10)=null,
@BTQuantity decimal=null,
@BTGrossWeight decimal=null,
@BTCarat varchar(4000)=null,
@BTNetWeight decimal=null,
@BTAmount decimal=null,
@BTDeduction decimal=null,
@BTNetAmount decimal=null,
@CTQuantity decimal=null,
@CTGrossWeight decimal=null,
@CTCarat varchar(4000)=null,
@CTNetWeight decimal=null,
@CTAmount decimal=null,
@CTDeduction decimal=null,
@CTNetAmount decimal=null,
@IsShowonPage varchar(10)=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@CreateBy int=null,
@CreateDate datetime=null,
@ModifyBy int=null,
@ModifyDate datetime=null,
@Sysdate datetime=null
)
AS
Insert Into 
BillMasters 
(
[fkBillID],
[fkAccountID],
[IsCompanyAccount],
[BillPaidStatus],
[IsCapital],
[BTQuantity],
[BTGrossWeight],
[BTCarat],
[BTNetWeight],
[BTAmount],
[BTDeduction],
[BTNetAmount],
[CTQuantity],
[CTGrossWeight],
[CTCarat],
[CTNetWeight],
[CTAmount],
[CTDeduction],
[CTNetAmount],
[IsShowonPage],
[fkBranchID],
[IsActive],
[CreateBy],
[CreateDate],
[ModifyBy],
[ModifyDate],
[Sysdate]
) 
values(
@fkBillID,
@fkAccountID,
@IsCompanyAccount,
@BillPaidStatus,
@IsCapital,
@BTQuantity,
@BTGrossWeight,
@BTCarat,
@BTNetWeight,
@BTAmount,
@BTDeduction,
@BTNetAmount,
@CTQuantity,
@CTGrossWeight,
@CTCarat,
@CTNetWeight,
@CTAmount,
@CTDeduction,
@CTNetAmount,
@IsShowonPage,
@fkBranchID,
@IsActive,
@CreateBy,
@CreateDate,
@ModifyBy,
@ModifyDate,
@Sysdate
)
RETURN Scope_identity()
