
CREATE PROCEDURE [dbo].[BillDetails_Insert] 
	(
@BillDetailNo bigint=null,
@BillDetailCode varchar(100)=null,
@fkBillID bigint=null,
@SNo int=null,
@fkItemTypeID int,
@ItemName nvarchar(500)=null,
@fkItemUnitID int,
@ItemUnit nvarchar(500)=null,
@ItemMarca nvarchar(50)=null,
@Quantity decimal=null,
@ActualRate decimal=null,
@BillRate decimal=null,
@WeightDetails varchar(4000)=null,
@BillWeightDetails varchar(4000)=null,
@GrossWeight decimal=null,
@BillGrossWeight decimal=null,
@NetWeight decimal=null,
@BillNetWeight decimal=null,
@SaleTypeFixOrWeightBased nvarchar(50)=null,
@CommissionAmount decimal=null,
@TotalWeightCutting decimal=null,
@TotalHammali decimal=null,
@TotalTulai decimal=null,
@TotalKhadiKari decimal=null,
@ActualTotalAmount decimal=null,
@BillTotalAmount decimal=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@CreateBy int=null,
@CreateDate datetime=null,
@ModifyBy int=null,
@ModifyDate datetime=null,
@CommissionPercent decimal=null,
@Sysdate datetime=null,
@AvgWeight decimal=null,
@CommissionPercentS decimal=null,
@CommissionAmountS decimal=null,
@AvgRate decimal=null
)
AS
Insert Into 
BillDetails 
(
[BillDetailNo],
[BillDetailCode],
[fkBillID],
[SNo],
[fkItemTypeID],
[ItemName],
[fkItemUnitID],
[ItemUnit],
[ItemMarca],
[Quantity],
[ActualRate],
[BillRate],
[WeightDetails],
[BillWeightDetails],
[GrossWeight],
[BillGrossWeight],
[NetWeight],
[BillNetWeight],
[SaleTypeFixOrWeightBased],
[CommissionAmount],
[TotalWeightCutting],
[TotalHammali],
[TotalTulai],
[TotalKhadiKari],
[ActualTotalAmount],
[BillTotalAmount],
[fkBranchID],
[IsActive],
[CreateBy],
[CreateDate],
[ModifyBy],
[ModifyDate],
[CommissionPercent],
[Sysdate],
[AvgWeight],
[CommissionPercentS],
[CommissionAmountS],
[AvgRate]
) 
values(
@BillDetailNo,
@BillDetailCode,
@fkBillID,
@SNo,
@fkItemTypeID,
@ItemName,
@fkItemUnitID,
@ItemUnit,
@ItemMarca,
@Quantity,
@ActualRate,
@BillRate,
@WeightDetails,
@BillWeightDetails,
@GrossWeight,
@BillGrossWeight,
@NetWeight,
@BillNetWeight,
@SaleTypeFixOrWeightBased,
@CommissionAmount,
@TotalWeightCutting,
@TotalHammali,
@TotalTulai,
@TotalKhadiKari,
@ActualTotalAmount,
@BillTotalAmount,
@fkBranchID,
@IsActive,
@CreateBy,
@CreateDate,
@ModifyBy,
@ModifyDate,
@CommissionPercent,
@Sysdate,
@AvgWeight,
@CommissionPercentS,
@CommissionAmountS,
@AvgRate
)
RETURN Scope_identity()
