
CREATE PROCEDURE [dbo].[BillPaymentDetails_Insert] 
	(
@fkBillID int=null,
@CompanyBankAccountID int=null,
@PaymentMode varchar(250)=null,
@CashAmount decimal=null,
@fkAccountBankDetailID int=null,
@ChequeDate datetime=null,
@ChequeNo varchar(250)=null,
@ChequeAmount decimal=null,
@BankAccountNo varchar(100)=null,
@BranchNo varchar(50)=null,
@BranchName varchar(50)=null,
@IfscCode varchar(50)=null,
@PanNo varchar(50)=null,
@AccountHolderName varchar(50)=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@InsertDate datetime=null,
@ModifyDate datetime=null,
@CreatedBy int=null,
@ModifiedBy int=null,
@TransactionNo varchar(250)=null,
@Remark varchar(250)=null,
@Sysdate datetime=null
)
AS
Insert Into 
BillPaymentDetails 
(
[fkBillID],
[CompanyBankAccountID],
[PaymentMode],
[CashAmount],
[fkAccountBankDetailID],
[ChequeDate],
[ChequeNo],
[ChequeAmount],
[BankAccountNo],
[BranchNo],
[BranchName],
[IfscCode],
[PanNo],
[AccountHolderName],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[TransactionNo],
[Remark],
[Sysdate]
) 
values(
@fkBillID,
@CompanyBankAccountID,
@PaymentMode,
@CashAmount,
@fkAccountBankDetailID,
@ChequeDate,
@ChequeNo,
@ChequeAmount,
@BankAccountNo,
@BranchNo,
@BranchName,
@IfscCode,
@PanNo,
@AccountHolderName,
@fkBranchID,
@IsActive,
@InsertDate,
@ModifyDate,
@CreatedBy,
@ModifiedBy,
@TransactionNo,
@Remark,
@Sysdate
)
RETURN Scope_identity()
