
CREATE PROCEDURE [dbo].[CashBooks_Insert] 
	(
@CashBookNo bigint=null,
@CashBookCode varchar(50)=null,
@CashBookDetail varchar(50)=null,
@VoucherNo bigint=null,
@VoucherType varchar(50)=null,
@CashorBankAccount varchar(50)=null,
@ChequeNo varchar(50)=null,
@RecieptType varchar(20)=null,
@fkAccountID bigint=null,
@fkAccountType int=null,
@fkVillageID int=null,
@VillageName varchar(50)=null,
@IsCompanyAccount varchar(50)=null,
@AccountHolder nvarchar(500)=null,
@TransactionDate datetime=null,
@TransactionDetail nvarchar(500)=null,
@Folio nvarchar(500)=null,
@DebitAmount decimal=null,
@CreditAmount decimal=null,
@IsDebitOrCredit nvarchar(50)=null,
@BalanceAmount decimal=null,
@Remark varchar(200)=null,
@Comment varchar(200)=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@InsertDate datetime=null,
@ModifyDate datetime=null,
@CreatedBy int=null,
@ModifiedBy int=null,
@fkBillID int=null,
@Sysdate datetime=null
)
AS
Insert Into 
CashBooks 
(
[CashBookNo],
[CashBookCode],
[CashBookDetail],
[VoucherNo],
[VoucherType],
[CashorBankAccount],
[ChequeNo],
[RecieptType],
[fkAccountID],
[fkAccountType],
[fkVillageID],
[VillageName],
[IsCompanyAccount],
[AccountHolder],
[TransactionDate],
[TransactionDetail],
[Folio],
[DebitAmount],
[CreditAmount],
[IsDebitOrCredit],
[BalanceAmount],
[Remark],
[Comment],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[fkBillID],
[Sysdate]
) 
values(
@CashBookNo,
@CashBookCode,
@CashBookDetail,
@VoucherNo,
@VoucherType,
@CashorBankAccount,
@ChequeNo,
@RecieptType,
@fkAccountID,
@fkAccountType,
@fkVillageID,
@VillageName,
@IsCompanyAccount,
@AccountHolder,
@TransactionDate,
@TransactionDetail,
@Folio,
@DebitAmount,
@CreditAmount,
@IsDebitOrCredit,
@BalanceAmount,
@Remark,
@Comment,
@fkBranchID,
@IsActive,
@InsertDate,
@ModifyDate,
@CreatedBy,
@ModifiedBy,
@fkBillID,
@Sysdate
)
RETURN Scope_identity()
