
CREATE PROCEDURE [dbo].[ExportItemDetails_UpdateByID] 
	(
@ExportItemDetailID int,
@ExportItemDetailNo int=null,
@ExportItemDetailCode varchar(100)=null,
@fkExportMasterID int=null,
@fkItemSaleDetailID int=null,
@ItemSaleDetails varchar(100)=null,
@IsCompanyAccount varchar(50)=null,
@fkAccountID bigint=null,
@PartyName varchar(250)=null,
@PartyShortName varchar(250)=null,
@fkItemTypeID int,
@ItemName nvarchar(500)=null,
@fkItemUnitID int,
@UnitName nvarchar(500)=null,
@Marca nvarchar(250)=null,
@TotalQuantity bigint=null,
@AcutualQuantity bigint=null,
@BillQuantity bigint=null,
@ActualRate decimal=null,
@BillRate decimal=null,
@GrossWeight decimal=null,
@BillGrossWeight decimal=null,
@NetWeight decimal=null,
@BillNetWeight decimal=null,
@TotalAmount decimal=null,
@BillTotalAmount decimal=null,
@CommissionPercent decimal=null,
@CommissionPercent2 decimal=null,
@BillCommissionPercent decimal=null,
@CommissionAmount decimal=null,
@BillCommissionAmount decimal=null,
@TotalHammali decimal=null,
@TotalTulai decimal=null,
@TotalKhadiKari decimal=null,
@NetAmount decimal=null,
@BillNetAmount decimal=null,
@TotalWeightCutting decimal=null,
@lotDetail nvarchar(250)=null,
@TotalCarat int=null,
@TotalCatte int=null,
@TotalBhada int=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@InsertDate datetime=null,
@ModifyDate datetime=null,
@CreatedBy int=null,
@ModifiedBy int=null,
@Sysdate datetime=null
)
AS
Update  ExportItemDetails Set 
[ExportItemDetailNo]=@ExportItemDetailNo,
[ExportItemDetailCode]=@ExportItemDetailCode,
[fkExportMasterID]=@fkExportMasterID,
[fkItemSaleDetailID]=@fkItemSaleDetailID,
[ItemSaleDetails]=@ItemSaleDetails,
[IsCompanyAccount]=@IsCompanyAccount,
[fkAccountID]=@fkAccountID,
[PartyName]=@PartyName,
[PartyShortName]=@PartyShortName,
[fkItemTypeID]=@fkItemTypeID,
[ItemName]=@ItemName,
[fkItemUnitID]=@fkItemUnitID,
[UnitName]=@UnitName,
[Marca]=@Marca,
[TotalQuantity]=@TotalQuantity,
[AcutualQuantity]=@AcutualQuantity,
[BillQuantity]=@BillQuantity,
[ActualRate]=@ActualRate,
[BillRate]=@BillRate,
[GrossWeight]=@GrossWeight,
[BillGrossWeight]=@BillGrossWeight,
[NetWeight]=@NetWeight,
[BillNetWeight]=@BillNetWeight,
[TotalAmount]=@TotalAmount,
[BillTotalAmount]=@BillTotalAmount,
[CommissionPercent]=@CommissionPercent,
[CommissionPercent2]=@CommissionPercent2,
[BillCommissionPercent]=@BillCommissionPercent,
[CommissionAmount]=@CommissionAmount,
[BillCommissionAmount]=@BillCommissionAmount,
[TotalHammali]=@TotalHammali,
[TotalTulai]=@TotalTulai,
[TotalKhadiKari]=@TotalKhadiKari,
[NetAmount]=@NetAmount,
[BillNetAmount]=@BillNetAmount,
[TotalWeightCutting]=@TotalWeightCutting,
[lotDetail]=@lotDetail,
[TotalCarat]=@TotalCarat,
[TotalCatte]=@TotalCatte,
[TotalBhada]=@TotalBhada,
[fkBranchID]=@fkBranchID,
[IsActive]=@IsActive,
[InsertDate]=@InsertDate,
[ModifyDate]=@ModifyDate,
[CreatedBy]=@CreatedBy,
[ModifiedBy]=@ModifiedBy,
[Sysdate]=@Sysdate
 
where 
[ExportItemDetailID]=@ExportItemDetailID


Return
