
CREATE PROCEDURE [dbo].[ExportMasters_Insert] 
	(
@ExportMasterNo int=null,
@ExportCode varchar(100)=null,
@ExportCodeDetail varchar(100)=null,
@fkAccountID bigint=null,
@BiltiNo int=null,
@IsExportBaki varchar(50)=null,
@IsExportBakiDetail varchar(250)=null,
@ExportMasterPaidStatus varchar(50)=null,
@BiltiDetail varchar(100)=null,
@BiltiDate datetime=null,
@ClientName nvarchar(500)=null,
@fkVillageID bigint=null,
@ClientCity nvarchar(500)=null,
@DriverName nvarchar(500)=null,
@DriverPhoneNo nvarchar(500)=null,
@DriverInam nvarchar(250)=null,
@GadiBhada decimal=null,
@AdvanceBhada decimal=null,
@RemainingBhada decimal=null,
@ReachDate datetime=null,
@TimeToReach nvarchar(250)=null,
@PerKattaBhada decimal=null,
@PerCaratBhada decimal=null,
@ParBoriBhada decimal=null,
@FakeMandiAmount decimal=null,
@FakeMandiPercent decimal=null,
@FakeMandiNetAmount decimal=null,
@TotalExportAmount decimal=null,
@TotalBillExportAmount decimal=null,
@TotalExpenses decimal=null,
@BillTotalExpenses decimal=null,
@NetExportAmount decimal=null,
@BillNetExportAmount decimal=null,
@GadiNo varchar(50)=null,
@TotalHammali decimal=null,
@MandiSulk decimal=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@InsertDate datetime=null,
@ModifyDate datetime=null,
@CreatedBy int=null,
@ModifiedBy int=null,
@Address varchar(1000)=null,
@Transport varchar(500)=null,
@Sysdate datetime=null
)
AS
Insert Into 
ExportMasters 
(
[ExportMasterNo],
[ExportCode],
[ExportCodeDetail],
[fkAccountID],
[BiltiNo],
[IsExportBaki],
[IsExportBakiDetail],
[ExportMasterPaidStatus],
[BiltiDetail],
[BiltiDate],
[ClientName],
[fkVillageID],
[ClientCity],
[DriverName],
[DriverPhoneNo],
[DriverInam],
[GadiBhada],
[AdvanceBhada],
[RemainingBhada],
[ReachDate],
[TimeToReach],
[PerKattaBhada],
[PerCaratBhada],
[ParBoriBhada],
[FakeMandiAmount],
[FakeMandiPercent],
[FakeMandiNetAmount],
[TotalExportAmount],
[TotalBillExportAmount],
[TotalExpenses],
[BillTotalExpenses],
[NetExportAmount],
[BillNetExportAmount],
[GadiNo],
[TotalHammali],
[MandiSulk],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[Address],
[Transport],
[Sysdate]
) 
values(
@ExportMasterNo,
@ExportCode,
@ExportCodeDetail,
@fkAccountID,
@BiltiNo,
@IsExportBaki,
@IsExportBakiDetail,
@ExportMasterPaidStatus,
@BiltiDetail,
@BiltiDate,
@ClientName,
@fkVillageID,
@ClientCity,
@DriverName,
@DriverPhoneNo,
@DriverInam,
@GadiBhada,
@AdvanceBhada,
@RemainingBhada,
@ReachDate,
@TimeToReach,
@PerKattaBhada,
@PerCaratBhada,
@ParBoriBhada,
@FakeMandiAmount,
@FakeMandiPercent,
@FakeMandiNetAmount,
@TotalExportAmount,
@TotalBillExportAmount,
@TotalExpenses,
@BillTotalExpenses,
@NetExportAmount,
@BillNetExportAmount,
@GadiNo,
@TotalHammali,
@MandiSulk,
@fkBranchID,
@IsActive,
@InsertDate,
@ModifyDate,
@CreatedBy,
@ModifiedBy,
@Address,
@Transport,
@Sysdate
)
RETURN Scope_identity()
