
CREATE PROCEDURE [dbo].[ExportMasters_UpdateByID] 
	(
@ExportMasterID int,
@ExportMasterNo int=null,
@ExportCode varchar(100)=null,
@ExportCodeDetail varchar(100)=null,
@fkAccountID bigint=null,
@BiltiNo int=null,
@IsExportBaki varchar(50)=null,
@IsExportBakiDetail varchar(250)=null,
@ExportMasterPaidStatus varchar(50)=null,
@BiltiDetail varchar(100)=null,
@BiltiDate datetime=null,
@ClientName nvarchar(500)=null,
@fkVillageID bigint=null,
@ClientCity nvarchar(500)=null,
@DriverName nvarchar(500)=null,
@DriverPhoneNo nvarchar(500)=null,
@DriverInam nvarchar(250)=null,
@GadiBhada decimal=null,
@AdvanceBhada decimal=null,
@RemainingBhada decimal=null,
@ReachDate datetime=null,
@TimeToReach nvarchar(250)=null,
@PerKattaBhada decimal=null,
@PerCaratBhada decimal=null,
@ParBoriBhada decimal=null,
@FakeMandiAmount decimal=null,
@FakeMandiPercent decimal=null,
@FakeMandiNetAmount decimal=null,
@TotalExportAmount decimal=null,
@TotalBillExportAmount decimal=null,
@TotalExpenses decimal=null,
@BillTotalExpenses decimal=null,
@NetExportAmount decimal=null,
@BillNetExportAmount decimal=null,
@GadiNo varchar(50)=null,
@TotalHammali decimal=null,
@MandiSulk decimal=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@InsertDate datetime=null,
@ModifyDate datetime=null,
@CreatedBy int=null,
@ModifiedBy int=null,
@Address varchar(1000)=null,
@Transport varchar(500)=null,
@Sysdate datetime=null
)
AS
Update  ExportMasters Set 
[ExportMasterNo]=@ExportMasterNo,
[ExportCode]=@ExportCode,
[ExportCodeDetail]=@ExportCodeDetail,
[fkAccountID]=@fkAccountID,
[BiltiNo]=@BiltiNo,
[IsExportBaki]=@IsExportBaki,
[IsExportBakiDetail]=@IsExportBakiDetail,
[ExportMasterPaidStatus]=@ExportMasterPaidStatus,
[BiltiDetail]=@BiltiDetail,
[BiltiDate]=@BiltiDate,
[ClientName]=@ClientName,
[fkVillageID]=@fkVillageID,
[ClientCity]=@ClientCity,
[DriverName]=@DriverName,
[DriverPhoneNo]=@DriverPhoneNo,
[DriverInam]=@DriverInam,
[GadiBhada]=@GadiBhada,
[AdvanceBhada]=@AdvanceBhada,
[RemainingBhada]=@RemainingBhada,
[ReachDate]=@ReachDate,
[TimeToReach]=@TimeToReach,
[PerKattaBhada]=@PerKattaBhada,
[PerCaratBhada]=@PerCaratBhada,
[ParBoriBhada]=@ParBoriBhada,
[FakeMandiAmount]=@FakeMandiAmount,
[FakeMandiPercent]=@FakeMandiPercent,
[FakeMandiNetAmount]=@FakeMandiNetAmount,
[TotalExportAmount]=@TotalExportAmount,
[TotalBillExportAmount]=@TotalBillExportAmount,
[TotalExpenses]=@TotalExpenses,
[BillTotalExpenses]=@BillTotalExpenses,
[NetExportAmount]=@NetExportAmount,
[BillNetExportAmount]=@BillNetExportAmount,
[GadiNo]=@GadiNo,
[TotalHammali]=@TotalHammali,
[MandiSulk]=@MandiSulk,
[fkBranchID]=@fkBranchID,
[IsActive]=@IsActive,
[InsertDate]=@InsertDate,
[ModifyDate]=@ModifyDate,
[CreatedBy]=@CreatedBy,
[ModifiedBy]=@ModifiedBy,
[Address]=@Address,
[Transport]=@Transport,
[Sysdate]=@Sysdate
 
where 
[ExportMasterID]=@ExportMasterID


Return
