
CREATE PROCEDURE [dbo].[ExportItemDetails_Insert] 
	(
@ExportItemDetailNo int=null,
@ExportItemDetailCode varchar(100)=null,
@fkExportMasterID int=null,
@fkItemSaleDetailID int=null,
@ItemSaleDetails varchar(100)=null,
@IsCompanyAccount varchar(50)=null,
@fkAccountID bigint=null,
@PartyName varchar(250)=null,
@PartyShortName varchar(250)=null,
@fkItemTypeID int,
@ItemName nvarchar(500)=null,
@fkItemUnitID int,
@UnitName nvarchar(500)=null,
@Marca nvarchar(250)=null,
@TotalQuantity bigint=null,
@AcutualQuantity bigint=null,
@BillQuantity bigint=null,
@ActualRate decimal=null,
@BillRate decimal=null,
@GrossWeight decimal=null,
@BillGrossWeight decimal=null,
@NetWeight decimal=null,
@BillNetWeight decimal=null,
@TotalAmount decimal=null,
@BillTotalAmount decimal=null,
@CommissionPercent decimal=null,
@CommissionPercent2 decimal=null,
@BillCommissionPercent decimal=null,
@CommissionAmount decimal=null,
@BillCommissionAmount decimal=null,
@TotalHammali decimal=null,
@TotalTulai decimal=null,
@TotalKhadiKari decimal=null,
@NetAmount decimal=null,
@BillNetAmount decimal=null,
@TotalWeightCutting decimal=null,
@lotDetail nvarchar(250)=null,
@TotalCarat int=null,
@TotalCatte int=null,
@TotalBhada int=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@InsertDate datetime=null,
@ModifyDate datetime=null,
@CreatedBy int=null,
@ModifiedBy int=null,
@Sysdate datetime=null
)
AS
Insert Into 
ExportItemDetails 
(
[ExportItemDetailNo],
[ExportItemDetailCode],
[fkExportMasterID],
[fkItemSaleDetailID],
[ItemSaleDetails],
[IsCompanyAccount],
[fkAccountID],
[PartyName],
[PartyShortName],
[fkItemTypeID],
[ItemName],
[fkItemUnitID],
[UnitName],
[Marca],
[TotalQuantity],
[AcutualQuantity],
[BillQuantity],
[ActualRate],
[BillRate],
[GrossWeight],
[BillGrossWeight],
[NetWeight],
[BillNetWeight],
[TotalAmount],
[BillTotalAmount],
[CommissionPercent],
[CommissionPercent2],
[BillCommissionPercent],
[CommissionAmount],
[BillCommissionAmount],
[TotalHammali],
[TotalTulai],
[TotalKhadiKari],
[NetAmount],
[BillNetAmount],
[TotalWeightCutting],
[lotDetail],
[TotalCarat],
[TotalCatte],
[TotalBhada],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[Sysdate]
) 
values(
@ExportItemDetailNo,
@ExportItemDetailCode,
@fkExportMasterID,
@fkItemSaleDetailID,
@ItemSaleDetails,
@IsCompanyAccount,
@fkAccountID,
@PartyName,
@PartyShortName,
@fkItemTypeID,
@ItemName,
@fkItemUnitID,
@UnitName,
@Marca,
@TotalQuantity,
@AcutualQuantity,
@BillQuantity,
@ActualRate,
@BillRate,
@GrossWeight,
@BillGrossWeight,
@NetWeight,
@BillNetWeight,
@TotalAmount,
@BillTotalAmount,
@CommissionPercent,
@CommissionPercent2,
@BillCommissionPercent,
@CommissionAmount,
@BillCommissionAmount,
@TotalHammali,
@TotalTulai,
@TotalKhadiKari,
@NetAmount,
@BillNetAmount,
@TotalWeightCutting,
@lotDetail,
@TotalCarat,
@TotalCatte,
@TotalBhada,
@fkBranchID,
@IsActive,
@InsertDate,
@ModifyDate,
@CreatedBy,
@ModifiedBy,
@Sysdate
)
RETURN Scope_identity()
