
CREATE PROCEDURE [dbo].[ItemSaleDetails_Insert] 
	(
@ItemSaleDetailNo bigint=null,
@ItemSaleCode varchar(100)=null,
@ItemSaleCodeDetail varchar(100)=null,
@fkAccountID bigint=null,
@PhoneNo varchar(50)=null,
@IsCompanyAccount varchar(50)=null,
@fkBillDetailID bigint,
@Quantity decimal=null,
@Rate decimal=null,
@SaleTypeFixOrWeightBased nvarchar(50)=null,
@GrossWeight decimal=null,
@WeightDetails varchar(4000)=null,
@NetWeight decimal=null,
@CommissionPercent decimal=null,
@CommissionAmount decimal=null,
@TotalAmount decimal=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@CreateBy int=null,
@CreateDate datetime=null,
@ModifyBy int=null,
@ModifyDate datetime=null,
@fkBillID bigint=null,
@Remark varchar=null,
@Comment varchar=null,
@Sysdate datetime=null
)
AS
Insert Into 
ItemSaleDetails 
(
[ItemSaleDetailNo],
[ItemSaleCode],
[ItemSaleCodeDetail],
[fkAccountID],
[PhoneNo],
[IsCompanyAccount],
[fkBillDetailID],
[Quantity],
[Rate],
[SaleTypeFixOrWeightBased],
[GrossWeight],
[WeightDetails],
[NetWeight],
[CommissionPercent],
[CommissionAmount],
[TotalAmount],
[fkBranchID],
[IsActive],
[CreateBy],
[CreateDate],
[ModifyBy],
[ModifyDate],
[fkBillID],
[Remark],
[Comment],
[Sysdate]
) 
values(
@ItemSaleDetailNo,
@ItemSaleCode,
@ItemSaleCodeDetail,
@fkAccountID,
@PhoneNo,
@IsCompanyAccount,
@fkBillDetailID,
@Quantity,
@Rate,
@SaleTypeFixOrWeightBased,
@GrossWeight,
@WeightDetails,
@NetWeight,
@CommissionPercent,
@CommissionAmount,
@TotalAmount,
@fkBranchID,
@IsActive,
@CreateBy,
@CreateDate,
@ModifyBy,
@ModifyDate,
@fkBillID,
@Remark,
@Comment,
@Sysdate
)
RETURN Scope_identity()
