
CREATE PROCEDURE [dbo].[ItemUnits_Insert] 
	(
@ItemUnitNo int=null,
@ItemUnit nvarchar(500)=null,
@ItemUnitHindi nvarchar(500)=null,
@RateOfUnitinKGS int=null,
@PercentComission decimal=null,
@WeightCuttingPerUnit decimal=null,
@HammaliPerUnit decimal=null,
@TulaiPerUnit decimal=null,
@KhadiKariPerUnit decimal=null,
@WeightCuttingPerUnit1 decimal=null,
@HammaliPerUnit1 decimal=null,
@TulaiPerUnit1 decimal=null,
@KhadiKariPerUnit1 decimal=null,
@WeightCuttingPerUnit2 decimal=null,
@HammaliPerUnit2 decimal=null,
@TulaiPerUnit2 decimal=null,
@KhadiKariPerUnit2 decimal=null,
@WeightCuttingPerUnit4 decimal=null,
@HammaliPerUnit4 decimal=null,
@TulaiPerUnit4 decimal=null,
@KhadiKariPerUnit4 decimal=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@CreateBy int=null,
@CreateDate datetime=null,
@ModifyBy int=null,
@ModifyDate datetime=null,
@Sysdate datetime=null
)
AS
Insert Into 
ItemUnits 
(
[ItemUnitNo],
[ItemUnit],
[ItemUnitHindi],
[RateOfUnitinKGS],
[PercentComission],
[WeightCuttingPerUnit],
[HammaliPerUnit],
[TulaiPerUnit],
[KhadiKariPerUnit],
[WeightCuttingPerUnit1],
[HammaliPerUnit1],
[TulaiPerUnit1],
[KhadiKariPerUnit1],
[WeightCuttingPerUnit2],
[HammaliPerUnit2],
[TulaiPerUnit2],
[KhadiKariPerUnit2],
[WeightCuttingPerUnit4],
[HammaliPerUnit4],
[TulaiPerUnit4],
[KhadiKariPerUnit4],
[fkBranchID],
[IsActive],
[CreateBy],
[CreateDate],
[ModifyBy],
[ModifyDate],
[Sysdate]
) 
values(
@ItemUnitNo,
@ItemUnit,
@ItemUnitHindi,
@RateOfUnitinKGS,
@PercentComission,
@WeightCuttingPerUnit,
@HammaliPerUnit,
@TulaiPerUnit,
@KhadiKariPerUnit,
@WeightCuttingPerUnit1,
@HammaliPerUnit1,
@TulaiPerUnit1,
@KhadiKariPerUnit1,
@WeightCuttingPerUnit2,
@HammaliPerUnit2,
@TulaiPerUnit2,
@KhadiKariPerUnit2,
@WeightCuttingPerUnit4,
@HammaliPerUnit4,
@TulaiPerUnit4,
@KhadiKariPerUnit4,
@fkBranchID,
@IsActive,
@CreateBy,
@CreateDate,
@ModifyBy,
@ModifyDate,
@Sysdate
)
RETURN Scope_identity()
