
CREATE PROCEDURE [dbo].[ItemSaleRateDiffs_UpdateByID] 
	(
@ItemSaleRateDiffID bigint,
@ItemSaleRateDiffNo bigint=null,
@ItemSaleRateDiffCode varchar(100)=null,
@ItemSaleRateDiffDetail varchar(100)=null,
@fkAccountID bigint=null,
@fkItemSaleDetailID bigint=null,
@IsCompanyAccount varchar(50)=null,
@fkBillDetailID bigint,
@Quantity decimal=null,
@Rate decimal=null,
@SaleTypeFixOrWeightBased nvarchar(50)=null,
@GrossWeight decimal=null,
@WeightDetails varchar(4000)=null,
@NetWeight decimal=null,
@CommissionPercent decimal=null,
@CommissionAmount decimal=null,
@TotalAmount decimal=null,
@NetAmount decimal=null,
@SQuantity decimal=null,
@SRate decimal=null,
@SSaleTypeFixOrWeightBased nvarchar(50)=null,
@SGrossWeight decimal=null,
@SWeightDetails varchar(4000)=null,
@SNetWeight decimal=null,
@SCommissionPercent decimal=null,
@SCommissionAmount decimal=null,
@STotalAmount decimal=null,
@SNetAmount decimal=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@CreateBy int=null,
@CreateDate datetime=null,
@ModifyBy int=null,
@ModifyDate datetime=null,
@fkBillID bigint=null,
@Sysdate datetime=null
)
AS
Update  ItemSaleRateDiffs Set 
[ItemSaleRateDiffNo]=@ItemSaleRateDiffNo,
[ItemSaleRateDiffCode]=@ItemSaleRateDiffCode,
[ItemSaleRateDiffDetail]=@ItemSaleRateDiffDetail,
[fkAccountID]=@fkAccountID,
[fkItemSaleDetailID]=@fkItemSaleDetailID,
[IsCompanyAccount]=@IsCompanyAccount,
[fkBillDetailID]=@fkBillDetailID,
[Quantity]=@Quantity,
[Rate]=@Rate,
[SaleTypeFixOrWeightBased]=@SaleTypeFixOrWeightBased,
[GrossWeight]=@GrossWeight,
[WeightDetails]=@WeightDetails,
[NetWeight]=@NetWeight,
[CommissionPercent]=@CommissionPercent,
[CommissionAmount]=@CommissionAmount,
[TotalAmount]=@TotalAmount,
[NetAmount]=@NetAmount,
[SQuantity]=@SQuantity,
[SRate]=@SRate,
[SSaleTypeFixOrWeightBased]=@SSaleTypeFixOrWeightBased,
[SGrossWeight]=@SGrossWeight,
[SWeightDetails]=@SWeightDetails,
[SNetWeight]=@SNetWeight,
[SCommissionPercent]=@SCommissionPercent,
[SCommissionAmount]=@SCommissionAmount,
[STotalAmount]=@STotalAmount,
[SNetAmount]=@SNetAmount,
[fkBranchID]=@fkBranchID,
[IsActive]=@IsActive,
[CreateBy]=@CreateBy,
[CreateDate]=@CreateDate,
[ModifyBy]=@ModifyBy,
[ModifyDate]=@ModifyDate,
[fkBillID]=@fkBillID,
[Sysdate]=@Sysdate
 
where 
[ItemSaleRateDiffID]=@ItemSaleRateDiffID


Return
