Create PROCEDURE [dbo].[ManageStocks_Get] 
AS
Select 
[ManageStockID],
[ManageStockNo],
[ManageStockCode],
[ManageStockDetail],
[fkAccountID],
[IsCompanyAccount],
[fkRefAccountID],
[fkBillDetailID],
[fkExportDetailID],
[fkItemTypeID],
[TransactionDate],
[TransactionDetail],
[DebitStock],
[CreditStock],
[IsDebitOrCredit],
[BalanceStock],
[RecieptType],
[Remark],
[Comment],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[Sysdate]

from 
ManageStocks
Return
