
CREATE PROCEDURE [dbo].[ManageHammalis_Insert] 
	(
@ManageHammaliNo bigint=null,
@ManageHammaliCode varchar(100)=null,
@ManageHammaliDetail varchar(100)=null,
@fkAccountID bigint=null,
@IsCompanyAccount varchar(50)=null,
@fkBillID int=null,
@fkExportID int=null,
@TransactionDate datetime=null,
@TransactionDetail varchar(250)=null,
@DebitHammali decimal=null,
@CreditHammali decimal=null,
@IsDebitOrCredit nvarchar(50)=null,
@BalanceHammali decimal=null,
@RecieptType varchar(20)=null,
@Remark varchar(200)=null,
@Comment varchar(200)=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@InsertDate datetime=null,
@ModifyDate datetime=null,
@CreatedBy int=null,
@ModifiedBy int=null,
@Sysdate datetime=null
)
AS
Insert Into 
ManageHammalis 
(
[ManageHammaliNo],
[ManageHammaliCode],
[ManageHammaliDetail],
[fkAccountID],
[IsCompanyAccount],
[fkBillID],
[fkExportID],
[TransactionDate],
[TransactionDetail],
[DebitHammali],
[CreditHammali],
[IsDebitOrCredit],
[BalanceHammali],
[RecieptType],
[Remark],
[Comment],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[Sysdate]
) 
values(
@ManageHammaliNo,
@ManageHammaliCode,
@ManageHammaliDetail,
@fkAccountID,
@IsCompanyAccount,
@fkBillID,
@fkExportID,
@TransactionDate,
@TransactionDetail,
@DebitHammali,
@CreditHammali,
@IsDebitOrCredit,
@BalanceHammali,
@RecieptType,
@Remark,
@Comment,
@fkBranchID,
@IsActive,
@InsertDate,
@ModifyDate,
@CreatedBy,
@ModifiedBy,
@Sysdate
)
RETURN Scope_identity()
