
CREATE PROCEDURE [dbo].[ManageStocks_Insert] 
	(
@ManageStockNo bigint=null,
@ManageStockCode varchar(100)=null,
@ManageStockDetail varchar(100)=null,
@fkAccountID bigint=null,
@IsCompanyAccount varchar(50)=null,
@fkRefAccountID bigint=null,
@fkBillDetailID bigint=null,
@fkExportDetailID bigint=null,
@fkItemTypeID int=null,
@TransactionDate datetime=null,
@TransactionDetail varchar(250)=null,
@DebitStock bigint=null,
@CreditStock bigint=null,
@IsDebitOrCredit nvarchar(50)=null,
@BalanceStock bigint=null,
@RecieptType varchar(20)=null,
@Remark varchar(200)=null,
@Comment varchar(200)=null,
@fkBranchID int=null,
@IsActive varchar(20)=null,
@InsertDate datetime=null,
@ModifyDate datetime=null,
@CreatedBy int=null,
@ModifiedBy int=null,
@Sysdate datetime=null
)
AS
Insert Into 
ManageStocks 
(
[ManageStockNo],
[ManageStockCode],
[ManageStockDetail],
[fkAccountID],
[IsCompanyAccount],
[fkRefAccountID],
[fkBillDetailID],
[fkExportDetailID],
[fkItemTypeID],
[TransactionDate],
[TransactionDetail],
[DebitStock],
[CreditStock],
[IsDebitOrCredit],
[BalanceStock],
[RecieptType],
[Remark],
[Comment],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[Sysdate]
) 
values(
@ManageStockNo,
@ManageStockCode,
@ManageStockDetail,
@fkAccountID,
@IsCompanyAccount,
@fkRefAccountID,
@fkBillDetailID,
@fkExportDetailID,
@fkItemTypeID,
@TransactionDate,
@TransactionDetail,
@DebitStock,
@CreditStock,
@IsDebitOrCredit,
@BalanceStock,
@RecieptType,
@Remark,
@Comment,
@fkBranchID,
@IsActive,
@InsertDate,
@ModifyDate,
@CreatedBy,
@ModifiedBy,
@Sysdate
)
RETURN Scope_identity()
