Create PROCEDURE [dbo].[ManageHammalis_Get] 
AS
Select 
[ManageHammaliID],
[ManageHammaliNo],
[ManageHammaliCode],
[ManageHammaliDetail],
[fkAccountID],
[IsCompanyAccount],
[fkBillID],
[fkExportID],
[TransactionDate],
[TransactionDetail],
[DebitHammali],
[CreditHammali],
[IsDebitOrCredit],
[BalanceHammali],
[RecieptType],
[Remark],
[Comment],
[fkBranchID],
[IsActive],
[InsertDate],
[ModifyDate],
[CreatedBy],
[ModifiedBy],
[Sysdate]

from 
ManageHammalis
Return
