CREATE TABLE [dbo].[Accounts] (
    [AccountID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [AccountNo]             BIGINT         NULL,
    [AccountFirmName]       NVARCHAR (500) NULL,
    [AccountFirmNameHindi]  NVARCHAR (500) NULL,
    [AccountSortName]       NVARCHAR (50)  NULL,
    [AccountHolderDetail]   NVARCHAR (500) NULL,
    [fkAccountTypeID]       INT            NULL,
    [AccountCode]           VARCHAR (50)   NULL,
    [AccountFirmCode]       VARCHAR (100)  NULL,
    [fkVillageID]           BIGINT         NULL,
    [AccountName]           NVARCHAR (500) NULL,
    [AccountNameHindi]      NVARCHAR (500) NULL,
    [AccountMobileNo]       NVARCHAR (100) NULL,
    [AccountPhoneNo]        NVARCHAR (100) NULL,
    [AccountAddress1]       NVARCHAR (500) NULL,
    [AccountAddress2]       NVARCHAR (500) NULL,
    [AccountCity]           NVARCHAR (100) NULL,
    [AccountState]          NVARCHAR (100) NULL,
    [AccountZip]            NVARCHAR (100) NULL,
    [AccountPanNo]          VARCHAR (50)   NULL,
    [IsShowonPage]          VARCHAR (10)   NULL,
    [fkBranchID]            INT            NULL,
    [IsActive]              VARCHAR (20)   CONSTRAINT [DF_Accounts_IsActive] DEFAULT ('Active') NULL,
    [InsertDate]            DATETIME       CONSTRAINT [DF_Accounts_InsertDate] DEFAULT (getdate()) NULL,
    [ModifyDate]            DATETIME       NULL,
    [CreatedBy]             INT            NULL,
    [ModifiedBy]            INT            NULL,
    [LicenceNo]             VARCHAR (250)  NULL,
    [EmailID]               VARCHAR (2000) NULL,
    [Sysdate]               DATETIME        CONSTRAINT [DF_Accounts_Sysdate]  DEFAULT (getdate()) NULL,
    [fkBankAccountID]       INT            NULL,
    [fkAccountBankDetailID] INT            NULL,
    [Remark]                VARCHAR (500)  NULL,
    CONSTRAINT [PK_Accounts_AccountID] PRIMARY KEY CLUSTERED ([AccountID] ASC),
    CONSTRAINT [FK_Accounts_AccountTypes_AccountTypeID] FOREIGN KEY ([fkAccountTypeID]) REFERENCES [dbo].[AccountTypes] ([AccountTypeID])
);

