CREATE TABLE [dbo].[AccountTransactionsHistory] (
    [AccountTransactionID]     BIGINT          NOT NULL,
    [AccountTransactionNo]     BIGINT          NULL,
    [AccountTransactionCode]   VARCHAR (50)    NULL,
    [AccountTransactionDetail] VARCHAR (50)    NULL,
    [VoucherNo]                BIGINT          NULL,
    [VoucherType]              VARCHAR (50)    NULL,
    [CashorBankAccount]        VARCHAR (50)    NULL,
    [ChequeNo]                 VARCHAR (50)    NULL,
    [RecieptType]              VARCHAR (20)    NULL,
    [fkAccountID]              BIGINT          NOT NULL,
    [fkAccountType]            INT             NULL,
    [fkVillageID]              INT             NULL,
    [VillageName]              VARCHAR (50)    NULL,
    [IsCompanyAccount]         VARCHAR (50)    NULL,
    [AccountHolder]            NVARCHAR (500)  NULL,
    [fkBillID]                 INT             NULL,
    [fkBillDetailID]           INT             NULL,
    [fkExportMasterID]         INT             NULL,
    [fkExportItemDetailID]     INT             NULL,
    [TransactionDate]          DATETIME        NULL,
    [TransactionDetail]        NVARCHAR (500)  NULL,
    [Folio]                    NVARCHAR (500)  NULL,
    [DebitAmount]              DECIMAL (18, 2) NULL,
    [CreditAmount]             DECIMAL (18, 2) NULL,
    [IsDebitOrCredit]          NVARCHAR (50)   NULL,
    [BalanceAmount]            DECIMAL (18, 2) NULL,
    [Remark]                   VARCHAR (200)   NULL,
    [Comment]                  VARCHAR (200)   NULL,
    [fkBranchID]               INT             NULL,
    [IsActive]                 VARCHAR (20)    NULL,
    [InsertDate]               DATETIME        NULL,
    [ModifyDate]               DATETIME        NULL,
    [CreatedBy]                INT             NULL,
    [ModifiedBy]               INT             NULL,
    [fkCashBookID]             INT             NULL,
    [fkItemSaleDetailID]       BIGINT          NULL,
    [PanaFlag]                 CHAR (1)        NULL,
    [PanaActualAmount]         FLOAT (53)      NULL,
    [PanaAspectedAmount]       FLOAT (53)      NULL,
    [PanaPaidAmount]           FLOAT (53)      NULL,
    [PanaDiscount]             FLOAT (53)      NULL,
    [PanaPercent]              INT             NULL,
    [PanaSystemPercent]        INT             NULL,
    [IsExport]                 BIT             NULL,
    [IsPurchase]               BIT             NULL,
    [IsSale]                   BIT             NULL,
    [RemarkItemSale]           FLOAT (53)      NULL,
    [PurchaseAmount]           FLOAT (53)      NULL,
    [SaleAmount]               FLOAT (53)      NULL,
    [RateDiffAmount]           FLOAT (53)      NULL,
    [Sysdate]                  DATETIME        CONSTRAINT [DF_AccountTransactionsHistory_Sysdate]  DEFAULT (getdate()) NULL,
    [fkBillPaymentID]          INT             NULL,
	[TableName]				   Varchar(250)	   NULL,
	[KeyColumn]				   Varchar(250)	   NULL,
	[KeyValue]				   Varchar(250)	   NULL,
	[KeyDescription]		   Varchar(250)	   NULL
    
);

