CREATE TABLE [dbo].[Bills] (
    [BillID]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [BillNo]                        BIGINT          NOT NULL,
    [BillCode]                      VARCHAR (100)   NULL,
    [BillCodeDetail]                VARCHAR (100)   NULL,
    [fkAccountID]                   BIGINT          NULL,
    [IsCompanyAccount]              VARCHAR (50)    NULL,
    [FirmPhoneNo]                   VARCHAR (50)    NULL,
    [BillRsvrPersonName]            VARCHAR (100)   NULL,
    [BillRsvrPhoneNo]               VARCHAR (50)    NULL,
    [fkVillageID]                   BIGINT          NULL,
    [VillageName]                   NVARCHAR (500)  NULL,
    [BillDate]                      DATETIME        NULL,
    [BillPaidStatus]                NVARCHAR (15)   NULL,
    [IsBillPrint]                   VARCHAR (10)    NULL,
    [fkBillTypeID]                  INT             NULL,
    [BillType]                      NVARCHAR (50)   NULL,
    [fkGadiMasterID]                INT             NULL,
    [TransPortName]                 NVARCHAR (500)  NULL,
    [GadiNo]                        NVARCHAR (50)   NULL,
    [IsBhadaPaid]                   VARCHAR (20)    NULL,
    [GadiBhada]                     DECIMAL (18, 2) NULL,
    [PreviousBalance]               DECIMAL (18, 2) NULL,
    [TotalSevaSulk]                 DECIMAL (18, 2) NULL,
    [TotalHammali]                  DECIMAL (18, 2) NULL,
    [TotalTulai]                    DECIMAL (18, 2) NULL,
    [TotalKhadiKarai]               DECIMAL (18, 2) NULL,
    [TotalInam]                     DECIMAL (18, 2) NULL,
    [TotalStationary]               DECIMAL (18, 2) NULL,
    [TotalPostageCharge]            DECIMAL (18, 2) NULL,
    [TotalOtherCharges]             DECIMAL (18, 2) NULL,
    [TotalPurchaseCommissionCharge] DECIMAL (18, 2) NULL,
    [TotalQuantity]                 DECIMAL (10)    NULL,
    [TotalAmount]                   DECIMAL (18, 2) NULL,
    [TotalDeduction]                DECIMAL (18, 2) NULL,
    [NetAmount]                     DECIMAL (18, 2) NULL,
    [PaidAmount]                    DECIMAL (18, 2) NULL,
    [BalanceAmount]                 DECIMAL (18, 2) NULL,
    [Discount]                      DECIMAL (18, 2) NULL,
    [SalesTax]                      DECIMAL (18, 2) NULL,
    [VatTax]                        DECIMAL (18, 2) NULL,
    [OtherTax]                      DECIMAL (18, 2) NULL,
    [Comments]                      NVARCHAR (100)  NULL,
    [PaymentMode]                   NVARCHAR (50)   NULL,
    [BillingAddress]                NVARCHAR (255)  NULL,
    [ShipingAddress]                NVARCHAR (255)  NULL,
    [fkBranchID]                    INT             NULL,
    [IsActive]                      VARCHAR (20)    CONSTRAINT [DF_Bills_IsActive] DEFAULT ('Active') NULL,
    [CreateBy]                      INT             NULL,
    [CreateDate]                    DATETIME        CONSTRAINT [DF_Bills_CreateDate] DEFAULT (getdate()) NULL,
    [ModifyBy]                      INT             NULL,
    [ModifyDate]                    DATETIME        NULL,
    [SendBillToMandiOffice]         VARCHAR (250)   NULL,
    [GateParchiNo]                  VARCHAR (250)   NULL,
    [AnubandNo]                     VARCHAR (250)   NULL,
    [TolParchiNo]                   VARCHAR (250)   NULL,
    [Other1]                        VARCHAR (250)   NULL,
    [Other2]                        VARCHAR (250)   NULL,
    [Other3]                        VARCHAR (250)   NULL,
    [Other4]                        VARCHAR (250)   NULL,
    [Other5]                        VARCHAR (250)   NULL,
    [AnubandNoSN]                   VARCHAR (250)   NULL,
    [TolParchiNoSN]                 VARCHAR (250)   NULL,
    [BhugtanNo]                     VARCHAR (250)   NULL,
    [BhugtanNoSN]                   VARCHAR (250)   NULL,
    [BookNo]                        VARCHAR (250)   NULL,
    [Sysdate]                       DATETIME        CONSTRAINT [DF_Bills_Sysdate] DEFAULT (getdate()) NULL,
    [AawakDate]                     DATE            NULL,
    [BiltiNo]                       VARCHAR (250)   NULL,
    [AddressDetail]                 VARCHAR (500)   NULL,
    [StateDetails]                  VARCHAR (500)   NULL,
    [BillPrintType]                 VARCHAR (500)   NULL,

	[TotalBarwai] [decimal] (10,2) NULL,
	[TotalMaidanHammali] [decimal] (10,2) NULL,
	[TotalPalaKarai] [decimal] (10,2) NULL,
	[TotalThelaBhada] [decimal] (10,2) NULL,
	[TotalBardan] [decimal] (10,2) NULL,
	[TotalAdvance] [decimal] (10,2) NULL,
	[TotalOthersExp] [decimal] (10,2) NULL,
	[TotalCommissionExp] [decimal] (10,2) NULL,

    CONSTRAINT [PK_Bills_BillID] PRIMARY KEY CLUSTERED ([BillID] ASC),
    CONSTRAINT [FK_Bills_Accounts_fkAccountID] FOREIGN KEY ([fkAccountID]) REFERENCES [dbo].[Accounts] ([AccountID])
);

