CREATE TABLE [dbo].[Configurations] (
    [ConfigurationID]    INT             IDENTITY (1, 1) NOT NULL,
    [ConfigurationNo]    INT             NULL,
    [CompanyAccountID]   INT             NULL,
    [HammaliAccountID]   INT             NULL,
    [PurchaseCommission] DECIMAL (10, 2) NULL,
    [SaleCommission]     DECIMAL (10, 2) NULL,
    [RateParKiloGram]    DECIMAL (10, 2) NULL,
    [Tax]                DECIMAL (10, 2) NULL,
    [SevaSulk]           DECIMAL (10, 2) NULL,
    [OtherCharges]       DECIMAL (10, 2) NULL,
    [Hammali]            DECIMAL (10, 2) NULL,
    [Tulai]              DECIMAL (10, 2) NULL,
    [KhadiKarai]         DECIMAL (10, 2) NULL,
    [Stationary]         DECIMAL (10, 2) NULL,
    [OtherExp]           DECIMAL (10, 2) NULL,
    [Other1]             DECIMAL (10, 2) NULL,
    [Other2]             DECIMAL (10, 2) NULL,
    [fkBranchID]         INT             NULL,
    [IsActive]           VARCHAR (20)    CONSTRAINT [DF_Configurations_IsActive] DEFAULT ('Active') NULL,
    [CreateBy]           INT             NULL,
    [CreateDate]         DATETIME        CONSTRAINT [DF_Configurations_CreateDate] DEFAULT (getdate()) NULL,
    [ModifyBy]           INT             NULL,
    [ModifyDate]         DATETIME        NULL,
    [TolPatrakNo]        VARCHAR (250)   NULL,
    [AnubandhNo]         VARCHAR (250)   NULL,
    [BhugtanNo]          VARCHAR (250)   NULL,
    [Sysdate]            DATETIME        CONSTRAINT [DF_Configurations_Sysdate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_Configurations_ConfigurationID] PRIMARY KEY CLUSTERED ([ConfigurationID] ASC)
);

