CREATE TABLE [dbo].[ExportItemDetails] (
    [ExportItemDetailID]    INT             IDENTITY (1, 1) NOT NULL,
    [ExportItemDetailNo]    INT             NULL,
    [ExportItemDetailCode]  VARCHAR (100)   NULL,
    [fkExportMasterID]      INT             NULL,
    [fkItemSaleDetailID]    INT             NULL,
    [ItemSaleDetails]       VARCHAR (100)   NULL,
    [IsCompanyAccount]      VARCHAR (50)    NULL,
    [fkAccountID]           BIGINT          NULL,
    [PartyName]             VARCHAR (250)   NULL,
    [PartyShortName]        VARCHAR (250)   NULL,
    [fkItemTypeID]          INT             NOT NULL,
    [ItemName]              NVARCHAR (500)  NULL,
    [fkItemUnitID]          INT             NOT NULL,
    [UnitName]              NVARCHAR (500)  NULL,
    [Marca]                 NVARCHAR (250)  NULL,
    [TotalQuantity]         BIGINT          NULL,
    [AcutualQuantity]       BIGINT          NULL,
    [BillQuantity]          BIGINT          NULL,
    [ActualRate]            DECIMAL (18, 2) NULL,
    [BillRate]              DECIMAL (18, 2) NULL,
    [GrossWeight]           DECIMAL (18, 2) NULL,
    [BillGrossWeight]       DECIMAL (18, 2) NULL,
    [NetWeight]             DECIMAL (18, 2) NULL,
    [BillNetWeight]         DECIMAL (18, 2) NULL,
    [TotalAmount]           DECIMAL (18, 2) NULL,
    [BillTotalAmount]       DECIMAL (18, 2) NULL,
    [CommissionPercent]     DECIMAL (18, 2) NULL,
    [CommissionPercent2]    DECIMAL (18, 2) NULL,
    [BillCommissionPercent] DECIMAL (18, 2) NULL,
    [CommissionAmount]      DECIMAL (18, 2) NULL,
    [BillCommissionAmount]  DECIMAL (18, 2) NULL,
    [TotalHammali]          DECIMAL (10, 2) NULL,
    [TotalTulai]            DECIMAL (10, 2) NULL,
    [TotalKhadiKari]        DECIMAL (10, 2) NULL,
    [NetAmount]             DECIMAL (18, 2) NULL,
    [BillNetAmount]         DECIMAL (18, 2) NULL,
    [TotalWeightCutting]    DECIMAL (10, 2) NULL,
    [lotDetail]             NVARCHAR (250)  NULL,
    [TotalCarat]            INT             NULL,
    [TotalCatte]            INT             NULL,
    [TotalBhada]            INT             NULL,
    [fkBranchID]            INT             NULL,
    [IsActive]              VARCHAR (20)    CONSTRAINT [DF_ExportItemDetails_IsActive] DEFAULT ('Active') NULL,
    [InsertDate]            DATETIME        CONSTRAINT [DF_ExportItemDetails_InsertDate] DEFAULT (getdate()) NULL,
    [ModifyDate]            DATETIME        NULL,
    [CreatedBy]             INT             NULL,
    [ModifiedBy]            INT             NULL,
    [Sysdate]               DATETIME        CONSTRAINT [DF_ExportItemDetails_Sysdate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ExportItemDetails_ExportItemDetailID] PRIMARY KEY CLUSTERED ([ExportItemDetailID] ASC)
);

