CREATE TABLE [dbo].[ItemUnits] (
    [ItemUnitID]            INT             IDENTITY (1, 1) NOT NULL,
    [ItemUnitNo]            INT             NULL,
    [ItemUnit]              NVARCHAR (500)  NULL,
    [ItemUnitHindi]         NVARCHAR (500)  NULL,
    [RateOfUnitinKGS]       INT             NULL,
    [PercentComission]      DECIMAL (10, 2) NULL,
    [WeightCuttingPerUnit]  DECIMAL (10, 2) NULL,
    [HammaliPerUnit]        DECIMAL (10, 2) NULL,
    [TulaiPerUnit]          DECIMAL (10, 2) NULL,
    [KhadiKariPerUnit]      DECIMAL (10, 2) NULL,
    [WeightCuttingPerUnit1] DECIMAL (10, 2) NULL,
    [HammaliPerUnit1]       DECIMAL (10, 2) NULL,
    [TulaiPerUnit1]         DECIMAL (10, 2) NULL,
    [KhadiKariPerUnit1]     DECIMAL (10, 2) NULL,
    [WeightCuttingPerUnit2] DECIMAL (10, 2) NULL,
    [HammaliPerUnit2]       DECIMAL (10, 2) NULL,
    [TulaiPerUnit2]         DECIMAL (10, 2) NULL,
    [KhadiKariPerUnit2]     DECIMAL (10, 2) NULL,
    [WeightCuttingPerUnit4] DECIMAL (10, 2) NULL,
    [HammaliPerUnit4]       DECIMAL (10, 2) NULL,
    [TulaiPerUnit4]         DECIMAL (10, 2) NULL,
    [KhadiKariPerUnit4]     DECIMAL (10, 2) NULL,
    [fkBranchID]            INT             NULL,
    [IsActive]              VARCHAR (20)    CONSTRAINT [DF_ItemUnits_IsActive] DEFAULT ('Active') NULL,
    [CreateBy]              INT             NULL,
    [CreateDate]            DATETIME        CONSTRAINT [DF_ItemUnits_CreateDate] DEFAULT (getdate()) NULL,
    [ModifyBy]              INT             NULL,
    [ModifyDate]            DATETIME        NULL,
    [Sysdate]               DATETIME        CONSTRAINT [DF_ItemUnits_Sysdate] DEFAULT (getdate()) NULL,
     CONSTRAINT [PK_ItemUnits_ItemUnitID]  PRIMARY KEY CLUSTERED ([ItemUnitID] ASC)
);

