CREATE TABLE [dbo].[ItemSaleSummary](
	[ItemSaleSummaryID] [bigint] IDENTITY(1,1) NOT NULL,
	[ItemSaleSummaryNo] [bigint] NULL,
	[ItemSaleCode] [varchar](100) NULL,
	[ItemSaleCodeDetail] [varchar](100) NULL,
	[TransactionDate] [datetime] NULL,
	[fkAccountID] [bigint] NULL,
	[Quantity] [decimal](10, 0) NULL,
	[GrossWeight] [decimal](18, 2) NULL,
	[NetWeight] [decimal](18, 2) NULL,
	[CommissionPercent] [decimal](18, 2) NULL,
	[CommissionAmount] [decimal](18, 2) NULL,
	[TotalAmount] [decimal](18, 2) NULL,
	[IsActive] [varchar](20) NULL,
	[CreateBy] [int] NULL,
	[CreateDate] [datetime] NULL,
	[ModifyBy] [int] NULL,
	[ModifyDate] [datetime] NULL,
	[Sysdate] [datetime] NULL,
	[PaidAmount] [decimal](10, 2) NULL,
	[Discount] [decimal](10, 2) NULL,
	[RemainingAmount] [decimal](10, 2) NULL,
	[IsPanaPaid] [varchar](50) NULL,
    CONSTRAINT [PK_ItemSaleSummary_ItemSaleSummaryID]  PRIMARY KEY CLUSTERED ([ItemSaleSummaryID] ASC)
)
