CREATE TABLE [dbo].[ItemSaleDetails] (
    [ItemSaleDetailID]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [ItemSaleDetailNo]         BIGINT          NULL,
    [ItemSaleCode]             VARCHAR (100)   NULL,
    [ItemSaleCodeDetail]       VARCHAR (100)   NULL,
    [fkAccountID]              BIGINT          NULL,
    [PhoneNo]                  VARCHAR (50)    NULL,
    [IsCompanyAccount]         VARCHAR (50)    NULL,
    [fkBillDetailID]           BIGINT          NOT NULL,
    [Quantity]                 DECIMAL (10)    NULL,
    [Rate]                     DECIMAL (18, 2) NULL,
    [SaleTypeFixOrWeightBased] NVARCHAR (50)   NULL,
    [GrossWeight]              DECIMAL (18, 2) NULL,
    [WeightDetails]            VARCHAR (4000)  NULL,
    [NetWeight]                DECIMAL (18, 2) NULL,
    [CommissionPercent]        DECIMAL (18, 2) NULL,
    [CommissionAmount]         DECIMAL (18, 2) NULL,
    [TotalAmount]              DECIMAL (18, 2) NULL,
    [fkBranchID]               INT             NULL,
    [IsActive]                 VARCHAR (20)    CONSTRAINT [DF_ItemSaleDetails_IsActive] DEFAULT ('Active') NULL,
    [CreateBy]                 INT             NULL,
    [CreateDate]               DATETIME        CONSTRAINT [DF_ItemSaleDetails_CreateDate] DEFAULT (getdate()) NULL,
    [ModifyBy]                 INT             NULL,
    [ModifyDate]               DATETIME        NULL,
    [fkBillID]                 BIGINT          NULL,
    [Remark]                   VARCHAR (MAX)   NULL,
    [Comment]                  VARCHAR (MAX)   NULL,
    [Sysdate]                  DATETIME        CONSTRAINT [DF_ItemSaleDetails_Sysdate] DEFAULT (getdate()) NULL,
	PaidAmount				   Decimal(10,2),
	Discount				   Decimal(10,2),
	RemainingAmount			   Decimal(10,2),
	IsPanaPaid				   bit,
    CONSTRAINT [PK_ItemSaleDetails_GadiMasterID]  PRIMARY KEY CLUSTERED ([ItemSaleDetailID] ASC),
    CONSTRAINT [FK_ItemSaleDetails_BillDetails_fkBillDetailID] FOREIGN KEY ([fkBillDetailID]) REFERENCES [dbo].[BillDetails] ([BillDetailID]),
    CONSTRAINT [FK_ItemSaleDetails_Accounts_fkAccountID] FOREIGN KEY ([fkAccountID]) REFERENCES [dbo].[Accounts] ([AccountID])
);

