CREATE TABLE [dbo].[ItemSaleDetailsHistory] (
    [ItemSaleDetailID]         BIGINT          NOT NULL,
    [ItemSaleDetailNo]         BIGINT          NULL,
    [ItemSaleCode]             VARCHAR (100)   NULL,
    [ItemSaleCodeDetail]       VARCHAR (100)   NULL,
    [fkAccountID]              BIGINT          NULL,
    [PhoneNo]                  VARCHAR (50)    NULL,
    [IsCompanyAccount]         VARCHAR (50)    NULL,
    [fkBillDetailID]           BIGINT          NOT NULL,
    [Quantity]                 DECIMAL (10)    NULL,
    [Rate]                     DECIMAL (18, 2) NULL,
    [SaleTypeFixOrWeightBased] NVARCHAR (50)   NULL,
    [GrossWeight]              DECIMAL (18, 2) NULL,
    [WeightDetails]            VARCHAR (4000)  NULL,
    [NetWeight]                DECIMAL (18, 2) NULL,
    [CommissionPercent]        DECIMAL (18, 2) NULL,
    [CommissionAmount]         DECIMAL (18, 2) NULL,
    [TotalAmount]              DECIMAL (18, 2) NULL,
    [fkBranchID]               INT             NULL,
    [IsActive]                 VARCHAR (20)    NULL,
    [CreateBy]                 INT             NULL,
    [CreateDate]               DATETIME        NULL,
    [ModifyBy]                 INT             NULL,
    [ModifyDate]               DATETIME        NULL,
    [fkBillID]                 BIGINT          NULL,
    [Remark]                   VARCHAR (MAX)   NULL,
    [Comment]                  VARCHAR (MAX)   NULL,
    [Sysdate]                  DATETIME        CONSTRAINT [DF_ItemSaleDetailsHistory_Sysdate]  DEFAULT (getdate()) NULL,
	PaidAmount				   Decimal(10,2),
	Discount				   Decimal(10,2),
	RemainingAmount			   Decimal(10,2),
	IsPanaPaid				   bit
);

