CREATE TABLE [dbo].[ManageStocks] (
    [ManageStockID]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [ManageStockNo]     BIGINT        NULL,
    [ManageStockCode]   VARCHAR (100) NULL,
    [ManageStockDetail] VARCHAR (100) NULL,
    [fkAccountID]       BIGINT        NULL,
    [IsCompanyAccount]  VARCHAR (50)  NULL,
    [fkRefAccountID]    BIGINT        NULL,
    [fkBillDetailID]    BIGINT        NULL,
    [fkExportDetailID]  BIGINT        NULL,
    [fkItemTypeID]      INT           NULL,
    [TransactionDate]   DATETIME      NULL,
    [TransactionDetail] VARCHAR (250) NULL,
    [DebitStock]        BIGINT        CONSTRAINT [DF_ManageStocks_DebitStock] DEFAULT ((0)) NULL,
    [CreditStock]       BIGINT        CONSTRAINT [DF_ManageStocks_CreditStock] DEFAULT ((0)) NULL,
    [IsDebitOrCredit]   NVARCHAR (50) NULL,
    [BalanceStock]      BIGINT        NULL,
    [RecieptType]       VARCHAR (20)  NULL,
    [Remark]            VARCHAR (200) NULL,
    [Comment]           VARCHAR (200) NULL,
    [fkBranchID]        INT           NULL,
    [IsActive]          VARCHAR (20)  CONSTRAINT [DF_ManageStocks_IsActive] DEFAULT ('Active') NULL,
    [InsertDate]        DATETIME      CONSTRAINT [DF_ManageStocks_InsertDate] DEFAULT (getdate()) NULL,
    [ModifyDate]        DATETIME      NULL,
    [CreatedBy]         INT           NULL,
    [ModifiedBy]        INT           NULL,
    [Sysdate]           DATETIME      CONSTRAINT [DF_ManageStocks_Sysdate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ManageStocks_ManageStockID] PRIMARY KEY CLUSTERED ([ManageStockID] ASC),
    CONSTRAINT [FK_ManageStocks_Accounts_fkAccountID] FOREIGN KEY ([fkAccountID]) REFERENCES [dbo].[Accounts] ([AccountID])
);

