CREATE TABLE [dbo].[ManageCarats] (
    [ManageCaratID]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [ManageCaratNo]     BIGINT          NULL,
    [ManageCaratCode]   VARCHAR (100)   NULL,
    [ManageCaratDetail] VARCHAR (100)   NULL,
    [fkAccountID]       BIGINT          NULL,
    [IsCompanyAccount]  VARCHAR (50)    NULL,
    [fkBillID]          INT             NULL,
    [fkExportID]        INT             NULL,
    [TransactionDate]   DATETIME        NULL,
    [TransactionDetail] VARCHAR (250)   NULL,
    [DebitCarat]        DECIMAL (18, 2) CONSTRAINT [DF_ManageCarats_DebitCarat] DEFAULT ((0)) NULL,
    [CreditCarat]       DECIMAL (18, 2) CONSTRAINT [DF_ManageCarats_CreditCarat] DEFAULT ((0)) NULL,
    [IsDebitOrCredit]   NVARCHAR (50)   NULL,
    [BalanceCarat]      INT             NULL,
    [RecieptType]       VARCHAR (20)    NULL,
    [Remark]            VARCHAR (200)   NULL,
    [Comment]           VARCHAR (200)   NULL,
    [fkBranchID]        INT             NULL,
    [IsActive]          VARCHAR (20)    CONSTRAINT [DF_ManageCarats_IsActive] DEFAULT ('Active') NULL,
    [InsertDate]        DATETIME        CONSTRAINT [DF_ManageCarats_InsertDate] DEFAULT (getdate()) NULL,
    [ModifyDate]        DATETIME        NULL,
    [CreatedBy]         INT             NULL,
    [ModifiedBy]        INT             NULL,
    [Sysdate]           DATETIME        CONSTRAINT [DF_ManageCarats_Sysdate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ManageCarats_ManageCaratID] PRIMARY KEY CLUSTERED ([ManageCaratID] ASC),
    CONSTRAINT [FK_ManageCarats_Accounts_fkAccountID] FOREIGN KEY ([fkAccountID]) REFERENCES [dbo].[Accounts] ([AccountID])
);

